import type { GameEntry } from '@/types/content'

export const games: GameEntry[] = [
  {
    slug: 'clair-obscur-expedition-33',
    title: 'Clair Obscur: Expedition 33',
    developer: 'Sandfall Interactive',
    publisher: 'Kepler Interactive',
    platforms: ['PC', 'PS5', 'Xbox'],
    genre: 'RPG',
    releaseDate: '2025-04-24',
    status: 'released',
    summary:
      'Turn-based RPG met parries, een stervende wereld en een expeditie die geen heldentocht is.',
    coverLabel: 'EXP33',
    related: [
      { collection: 'reviews', slug: 'clair-obscur-expedition-33' },
      { collection: 'features', slug: 'turn-based-is-niet-dood' },
    ],
    seo: {
      title: 'Clair Obscur: Expedition 33 — gamepagina',
      description: 'Platforms, release en ASAPxGaming-coverage van Expedition 33.',
    },
  },
  {
    slug: 'hollow-knight-silksong',
    title: 'Hollow Knight: Silksong',
    developer: 'Team Cherry',
    publisher: 'Team Cherry',
    platforms: ['PC', 'Switch', 'PS5', 'Xbox'],
    genre: 'Metroidvania',
    releaseDate: '2025-09-04',
    status: 'released',
    summary: 'Hornet in Pharloom. Sneller, gemeener, geen Hallownest-kloon.',
    coverLabel: 'SILK',
    related: [{ collection: 'reviews', slug: 'hollow-knight-silksong' }],
    seo: {
      title: 'Hollow Knight: Silksong — gamepagina',
      description: 'Silksong bij ASAPxGaming: platforms, release en review.',
    },
  },
  {
    slug: 'death-stranding-2',
    title: 'Death Stranding 2: On the Beach',
    developer: 'Kojima Productions',
    publisher: 'Sony',
    platforms: ['PS5', 'PC'],
    genre: 'Action',
    releaseDate: '2025-06-26',
    status: 'released',
    summary: 'Meer wegen, meer setpieces, dezelfde connecting-fantasy.',
    coverLabel: 'DS2',
    related: [{ collection: 'reviews', slug: 'death-stranding-2' }],
    seo: {
      title: 'Death Stranding 2 — gamepagina',
      description: 'DS2 bij ASAPxGaming: platforms, release en review.',
    },
  },
  {
    slug: 'split-fiction',
    title: 'Split Fiction',
    developer: 'Hazelight',
    publisher: 'EA',
    platforms: ['PC', 'PS5', 'Xbox'],
    genre: 'Co-op avontuur',
    releaseDate: '2025-03-06',
    status: 'released',
    summary: 'Twee spelers, twee genres, geen solo-excuse.',
    coverLabel: 'SPLIT',
    related: [{ collection: 'reviews', slug: 'split-fiction' }],
    seo: {
      title: 'Split Fiction — gamepagina',
      description: 'Split Fiction bij ASAPxGaming: co-op-avontuur, platforms en review.',
    },
  },
  {
    slug: 'mario-kart-world',
    title: 'Mario Kart World',
    developer: 'Nintendo',
    publisher: 'Nintendo',
    platforms: ['Switch'],
    genre: 'Racing',
    releaseDate: '2025-12-05',
    status: 'released',
    summary: 'Open routes, oude tilt, woonkamer-chaos.',
    coverLabel: 'MKW',
    related: [
      { collection: 'reviews', slug: 'mario-kart-world' },
      { collection: 'news', slug: 'mario-kart-world-online-seizoen' },
    ],
    seo: {
      title: 'Mario Kart World — gamepagina',
      description: 'Mario Kart World bij ASAPxGaming: Switch-release, review en nieuws.',
    },
  },
  {
    slug: 'polder-ghost-line',
    title: 'Polder Ghost Line',
    developer: 'Fietslamp Studio',
    publisher: 'Fietslamp Studio',
    platforms: ['PC', 'Switch'],
    genre: 'Horror',
    releaseDate: '2026-10-31',
    status: 'upcoming',
    summary:
      'Nederlandse fiets-horror door de mist. Demo speelbaar; full release rond Halloween 2026.',
    coverLabel: 'PGL',
    related: [{ collection: 'news', slug: 'nederlandse-indies-spotlight' }],
    seo: {
      title: 'Polder Ghost Line — gamepagina',
      description: 'Upcoming NL-indie Polder Ghost Line: platforms, geplande release, coverage.',
    },
  },
  {
    slug: 'wolverine-marvel',
    title: 'Marvel’s Wolverine',
    developer: 'Insomniac',
    publisher: 'Sony',
    platforms: ['PS5'],
    genre: 'Action',
    releaseDate: '2026-11-20',
    status: 'upcoming',
    summary:
      'Aangekondigde Insomniac-titel. ASAPxGaming reviewt hem als de reviewcode er is — niet op trailer-gevoel.',
    coverLabel: 'WOLV',
    related: [{ collection: 'features', slug: 'hype-zonder-build' }],
    seo: {
      title: 'Marvel’s Wolverine — gamepagina',
      description: 'Release-window en ASAPxGaming-beleid: geen review zonder build.',
    },
  },
  {
    slug: 'pragmata',
    title: 'Pragmata',
    developer: 'Capcom',
    publisher: 'Capcom',
    platforms: ['PC', 'PS5', 'Xbox'],
    genre: 'Action',
    releaseDate: '2026-12-04',
    status: 'upcoming',
    summary: 'Capcom sci-fi. Datum onder voorbehoud; we houden de kalender bij, geen hype-recap.',
    coverLabel: 'PRAG',
    related: [],
    seo: {
      title: 'Pragmata — gamepagina',
      description: 'Pragmata in de ASAPxGaming-releasekalender, platforms en status.',
    },
  },
]
