import type { GameEntry } from '@/types/content'

export const games: GameEntry[] = [
  {
    slug: 'clair-obscur-expedition-33',
    title: 'Clair Obscur: Expedition 33',
    developer: 'Sandfall Interactive',
    publisher: 'Kepler Interactive',
    platforms: ['PC', 'PS5', 'Xbox'],
    genre: 'RPG',
    releaseDate: '2025-04-24',
    status: 'released',
    summary: 'Turn-based RPG met parries en de Gommage. Onze review: 9.0.',
    coverLabel: 'EXP33',
    coverImage: '/covers/clair-obscur-expedition-33.jpg',
    related: [
      { collection: 'reviews', slug: 'clair-obscur-expedition-33' },
      { collection: 'news', slug: 'turn-based-is-niet-dood' },
    ],
    seo: {
      title: 'Clair Obscur: Expedition 33 — coverage',
      description: 'Release 24 april 2025, platforms en ASAPxGaming-review 9.0.',
    },
  },
  {
    slug: 'hollow-knight-silksong',
    title: 'Hollow Knight: Silksong',
    developer: 'Team Cherry',
    publisher: 'Team Cherry',
    platforms: ['PC', 'Switch', 'PS5', 'Xbox'],
    genre: 'Metroidvania',
    releaseDate: '2025-09-04',
    status: 'released',
    summary: 'Hornet in Pharloom. Onze review: 8.9, met een voetnoot bij de runbacks.',
    coverLabel: 'SILK',
    coverImage: '/covers/hollow-knight-silksong.jpg',
    related: [{ collection: 'reviews', slug: 'hollow-knight-silksong' }],
    seo: {
      title: 'Hollow Knight: Silksong — coverage',
      description: 'Release 4 september 2025 en ASAPxGaming-review 8.9.',
    },
  },
  {
    slug: 'death-stranding-2',
    title: 'Death Stranding 2: On the Beach',
    developer: 'Kojima Productions',
    publisher: 'Sony',
    platforms: ['PS5', 'PC'],
    genre: 'Action',
    releaseDate: '2025-06-26',
    status: 'released',
    summary: 'Connecting met meer wegen en meer cutscenes. Review: 8.7.',
    coverLabel: 'DS2',
    coverImage: '/covers/death-stranding-2.jpg',
    related: [{ collection: 'reviews', slug: 'death-stranding-2' }],
    seo: {
      title: 'Death Stranding 2 — coverage',
      description: 'Release 26 juni 2025, PS5/pc, ASAPxGaming-review 8.7.',
    },
  },
  {
    slug: 'split-fiction',
    title: 'Split Fiction',
    developer: 'Hazelight',
    publisher: 'EA',
    platforms: ['PC', 'PS5', 'Xbox'],
    genre: 'Co-op avontuur',
    releaseDate: '2025-03-06',
    status: 'released',
    summary: 'Twee spelers, twee genres. Review: 8.8 — solo is een etalage.',
    coverLabel: 'SPLIT',
    coverImage: '/covers/split-fiction.jpg',
    related: [{ collection: 'reviews', slug: 'split-fiction' }],
    seo: {
      title: 'Split Fiction — coverage',
      description: 'Release 6 maart 2025 en ASAPxGaming-review 8.8.',
    },
  },
  {
    slug: 'mario-kart-world',
    title: 'Mario Kart World',
    developer: 'Nintendo',
    publisher: 'Nintendo',
    platforms: ['Switch'],
    genre: 'Racing',
    releaseDate: '2025-06-05',
    status: 'released',
    summary: 'Switch 2-launchkart. Knockout Tour wint, Free Roam niet. Review: 8.4.',
    coverLabel: 'MKW',
    coverImage: '/covers/mario-kart-world.jpg',
    related: [
      { collection: 'reviews', slug: 'mario-kart-world' },
      { collection: 'news', slug: 'mario-kart-world-online-seizoen' },
    ],
    seo: {
      title: 'Mario Kart World — coverage',
      description: 'Release 5 juni 2025 op Switch 2, ASAPxGaming-review 8.4.',
    },
  },
  {
    slug: 'pragmata',
    title: 'Pragmata',
    developer: 'Capcom',
    publisher: 'Capcom',
    platforms: ['PC', 'PS5', 'Xbox', 'Switch'],
    genre: 'Action',
    releaseDate: '2026-04-17',
    status: 'released',
    summary: 'Hugh en Diana op de maan. Uit 17 april 2026. Review: 8.5.',
    coverLabel: 'PRAG',
    coverImage: '/covers/pragmata.jpg',
    related: [{ collection: 'reviews', slug: 'pragmata' }],
    seo: {
      title: 'Pragmata — coverage',
      description: 'Capcom sci-fi, release 17 april 2026, ASAPxGaming-review 8.5.',
    },
  },
  {
    slug: 'wolverine-marvel',
    title: 'Marvel’s Wolverine',
    developer: 'Insomniac',
    publisher: 'Sony',
    platforms: ['PS5'],
    genre: 'Action',
    releaseDate: '2026-09-15',
    status: 'released',
    summary: 'PS5-exclusief vanaf 15 september 2026. Review: 7.7 — hit, geen must-play.',
    coverLabel: 'WOLV',
    coverImage: '/covers/wolverine-marvel.jpg',
    related: [
      { collection: 'reviews', slug: 'wolverine-marvel' },
      { collection: 'news', slug: 'wolverine-ps5-launch' },
    ],
    seo: {
      title: 'Marvel’s Wolverine — coverage',
      description: 'PS5-release 15 september 2026 en ASAPxGaming-review 7.7.',
    },
  },
  {
    slug: 'polder-ghost-line',
    title: 'Polder Ghost Line',
    developer: 'Fietslamp Studio',
    publisher: 'Fietslamp Studio',
    platforms: ['PC', 'Switch'],
    genre: 'Horror',
    releaseDate: '2026-10-31',
    status: 'upcoming',
    summary: 'Nederlandse fiets-horror. Demo speelbaar; full release rond Halloween 2026. Geen review tot de build af is.',
    coverLabel: 'PGL',
    related: [{ collection: 'news', slug: 'nederlandse-indies-spotlight' }],
    seo: {
      title: 'Polder Ghost Line — kalender',
      description: 'Geplande release 31 oktober 2026, pc en Switch, coverage zonder hype-recap.',
    },
  },
  {
    slug: 'grand-theft-auto-vi',
    title: 'Grand Theft Auto VI',
    developer: 'Rockstar Games',
    publisher: 'Take-Two',
    platforms: ['PS5', 'Xbox'],
    genre: 'Action',
    releaseDate: '2026-11-19',
    status: 'upcoming',
    summary:
      'Officieel 19 november 2026, PS5 en Xbox Series. Geen review, geen lek-screenshots, wel de datum van Rockstar zelf.',
    coverLabel: 'GTA',
    coverImage: '/covers/grand-theft-auto-vi.jpg',
    related: [{ collection: 'news', slug: 'gta-vi-wachtkamer' }],
    seo: {
      title: 'GTA VI — kalender',
      description: 'Grand Theft Auto VI: 19 november 2026, PS5 en Xbox Series. ASAPxGaming volgt de officiële datum.',
    },
  },
]
