import type { GameEntry } from '@/types/content'

export const games: GameEntry[] = [
  {
    slug: 'resident-evil-requiem',
    title: 'Resident Evil Requiem',
    developer: 'Capcom',
    publisher: 'Capcom',
    platforms: ['PC', 'PS5', 'Xbox', 'Switch 2'],
    genre: 'Horror',
    releaseDate: '2026-02-27',
    status: 'released',
    summary: 'Negende hoofdstuk, 27 februari 2026. Grace Ashcroft en Leon S. Kennedy. Review: 8.7.',
    coverLabel: 'REQ',
    related: [{ collection: 'reviews', slug: 'resident-evil-requiem' }],
    seo: {
      title: 'Resident Evil Requiem coverage',
      description: 'Release 27 februari 2026 en ASAPxGaming review 8.7.',
    },
  },
  {
    slug: 'pragmata',
    title: 'Pragmata',
    developer: 'Capcom',
    publisher: 'Capcom',
    platforms: ['PC', 'PS5', 'Xbox', 'Switch'],
    genre: 'Action',
    releaseDate: '2026-04-17',
    status: 'released',
    summary: 'Hugh en Diana op de maan. Uit 17 april 2026. Review: 8.5.',
    coverLabel: 'PRAG',
    coverImage: '/covers/pragmata.jpg',
    related: [{ collection: 'reviews', slug: 'pragmata' }],
    seo: {
      title: 'Pragmata coverage',
      description: 'Capcom sci fi, release 17 april 2026, ASAPxGaming review 8.5.',
    },
  },
  {
    slug: 'forza-horizon-6',
    title: 'Forza Horizon 6',
    developer: 'Playground Games',
    publisher: 'Xbox Game Studios',
    platforms: ['PC', 'Xbox'],
    genre: 'Racing',
    releaseDate: '2026-05-19',
    status: 'released',
    summary: 'Japan festival, 19 mei 2026 op Xbox en pc. PS5 later in 2026. Review: 8.9.',
    coverLabel: 'FH6',
    related: [
      { collection: 'reviews', slug: 'forza-horizon-6' },
      { collection: 'news', slug: 'forza-ps5-blijft-2026' },
    ],
    seo: {
      title: 'Forza Horizon 6 coverage',
      description: 'Release 19 mei 2026 Xbox en pc, ASAPxGaming review 8.9.',
    },
  },
  {
    slug: '007-first-light',
    title: '007 First Light',
    developer: 'IO Interactive',
    publisher: 'IO Interactive',
    platforms: ['PC', 'PS5', 'Xbox'],
    genre: 'Action',
    releaseDate: '2026-05-27',
    status: 'released',
    summary: 'Jonge Bond, 27 mei 2026. Switch 2 verschoven naar maart 2027. Review: 8.6.',
    coverLabel: '007',
    related: [
      { collection: 'reviews', slug: '007-first-light' },
      { collection: 'news', slug: 'bond-switch-verschuift' },
    ],
    seo: {
      title: '007 First Light coverage',
      description: 'Release 27 mei 2026, ASAPxGaming review 8.6.',
    },
  },
  {
    slug: 'moonlighter-2',
    title: 'Moonlighter 2',
    developer: 'Digital Sun',
    publisher: 'Digital Sun',
    platforms: ['PC', 'PS5', 'Xbox', 'Switch 2'],
    genre: 'Indie',
    releaseDate: '2026-09-02',
    status: 'released',
    summary: 'Winkel overdag, dungeon s nachts. Uit 2 september 2026. Review: 8.2.',
    coverLabel: 'MOON',
    related: [
      { collection: 'reviews', slug: 'moonlighter-2' },
      { collection: 'news', slug: 'moonlighter-2-is-uit' },
    ],
    seo: {
      title: 'Moonlighter 2 coverage',
      description: 'Release 2 september 2026 en ASAPxGaming review 8.2.',
    },
  },
  {
    slug: 'wolverine-marvel',
    title: 'Marvel’s Wolverine',
    developer: 'Insomniac',
    publisher: 'Sony',
    platforms: ['PS5'],
    genre: 'Action',
    releaseDate: '2026-09-15',
    status: 'released',
    summary: 'Alleen PS5 vanaf 15 september 2026. Review: 7.7. Hit, geen must play.',
    coverLabel: 'WOLV',
    coverImage: '/covers/wolverine-marvel.jpg',
    related: [
      { collection: 'reviews', slug: 'wolverine-marvel' },
      { collection: 'news', slug: 'wolverine-is-uit' },
    ],
    seo: {
      title: 'Marvel’s Wolverine coverage',
      description: 'PS5 release 15 september 2026 en ASAPxGaming review 7.7.',
    },
  },
  {
    slug: 'fire-emblem-fortunes-weave',
    title: 'Fire Emblem: Fortune’s Weave',
    developer: 'Intelligent Systems',
    publisher: 'Nintendo',
    platforms: ['Switch 2'],
    genre: 'Strategy',
    releaseDate: '2026-09-17',
    status: 'upcoming',
    summary: 'Switch 2, 17 september 2026 volgens de gedateerde GameSpot lijst.',
    coverLabel: 'FE',
    related: [{ collection: 'news', slug: 'fire-emblem-overmorgen' }],
    seo: {
      title: 'Fire Emblem Fortune’s Weave kalender',
      description: 'Gedateerde release 17 september 2026, Switch 2.',
    },
  },
  {
    slug: 'control-resonant',
    title: 'Control Resonant',
    developer: 'Remedy',
    publisher: '505 Games',
    platforms: ['PC', 'PS5', 'Xbox'],
    genre: 'Action',
    releaseDate: '2026-09-24',
    status: 'upcoming',
    summary: '24 september 2026 op PS5, Xbox Series en pc. Gedateerd, geen undated bak.',
    coverLabel: 'CTRL',
    related: [{ collection: 'news', slug: 'september-na-wolverine' }],
    seo: {
      title: 'Control Resonant kalender',
      description: 'Gedateerde release 24 september 2026.',
    },
  },
  {
    slug: 'silent-hill-townfall',
    title: 'Silent Hill: Townfall',
    developer: 'No Code',
    publisher: 'Konami',
    platforms: ['PC', 'PS5'],
    genre: 'Horror',
    releaseDate: '2026-09-24',
    status: 'upcoming',
    summary: '24 september 2026, PS5 en pc, op de gedateerde lijst.',
    coverLabel: 'TOWN',
    related: [{ collection: 'news', slug: 'september-na-wolverine' }],
    seo: {
      title: 'Silent Hill Townfall kalender',
      description: 'Gedateerde release 24 september 2026, PS5 en pc.',
    },
  },
  {
    slug: 'minecraft-dungeons-2',
    title: 'Minecraft Dungeons 2',
    developer: 'Mojang',
    publisher: 'Xbox Game Studios',
    platforms: ['PC', 'PS5', 'Xbox', 'Switch 2'],
    genre: 'Action',
    releaseDate: '2026-09-29',
    status: 'upcoming',
    summary: '29 september 2026. Gedateerd op de GameSpot lijst.',
    coverLabel: 'DUN2',
    related: [{ collection: 'news', slug: 'september-na-wolverine' }],
    seo: {
      title: 'Minecraft Dungeons 2 kalender',
      description: 'Gedateerde release 29 september 2026.',
    },
  },
  {
    slug: 'ace-combat-8',
    title: 'Ace Combat 8: Wings of Theve',
    developer: 'Bandai Namco',
    publisher: 'Bandai Namco',
    platforms: ['PC', 'PS5', 'Xbox'],
    genre: 'Action',
    releaseDate: '2026-10-02',
    status: 'upcoming',
    summary: '2 oktober 2026. Wings of Theve, gedateerd.',
    coverLabel: 'ACE8',
    related: [{ collection: 'news', slug: 'oktober-is-dichtbij' }],
    seo: {
      title: 'Ace Combat 8 kalender',
      description: 'Gedateerde release 2 oktober 2026.',
    },
  },
  {
    slug: 'gears-of-war-e-day',
    title: 'Gears of War: E Day',
    developer: 'The Coalition',
    publisher: 'Xbox Game Studios',
    platforms: ['PC', 'Xbox'],
    genre: 'Shooter',
    releaseDate: '2026-10-06',
    status: 'upcoming',
    summary: '6 oktober 2026 op Xbox Series en pc.',
    coverLabel: 'GEARS',
    related: [{ collection: 'news', slug: 'oktober-is-dichtbij' }],
    seo: {
      title: 'Gears of War E Day kalender',
      description: 'Gedateerde release 6 oktober 2026.',
    },
  },
  {
    slug: 'final-fantasy-resonance',
    title: 'Final Fantasy Resonance',
    developer: 'Square Enix',
    publisher: 'Square Enix',
    platforms: ['PC', 'PS5', 'Xbox', 'Switch', 'Switch 2'],
    genre: 'RPG',
    releaseDate: '2026-10-22',
    status: 'upcoming',
    summary: '22 oktober 2026, breed op consoles en pc.',
    coverLabel: 'FFR',
    related: [{ collection: 'news', slug: 'oktober-is-dichtbij' }],
    seo: {
      title: 'Final Fantasy Resonance kalender',
      description: 'Gedateerde release 22 oktober 2026.',
    },
  },
  {
    slug: 'nintendo-switch-sports-resort',
    title: 'Nintendo Switch Sports Resort',
    developer: 'Nintendo',
    publisher: 'Nintendo',
    platforms: ['Switch 2'],
    genre: 'Sport',
    releaseDate: '2026-10-22',
    status: 'upcoming',
    summary: '22 oktober 2026, alleen Switch 2.',
    coverLabel: 'SPORT',
    related: [{ collection: 'news', slug: 'oktober-is-dichtbij' }],
    seo: {
      title: 'Nintendo Switch Sports Resort kalender',
      description: 'Gedateerde release 22 oktober 2026 op Switch 2.',
    },
  },
  {
    slug: 'call-of-duty-modern-warfare-4',
    title: 'Call of Duty: Modern Warfare 4',
    developer: 'Infinity Ward',
    publisher: 'Activision',
    platforms: ['PC', 'PS5', 'Xbox', 'Switch 2'],
    genre: 'Shooter',
    releaseDate: '2026-10-23',
    status: 'upcoming',
    summary: '23 oktober 2026. Gedateerd, geen undated rumor.',
    coverLabel: 'MW4',
    related: [{ collection: 'news', slug: 'oktober-is-dichtbij' }],
    seo: {
      title: 'Call of Duty Modern Warfare 4 kalender',
      description: 'Gedateerde release 23 oktober 2026.',
    },
  },
  {
    slug: 'phantom-blade-zero',
    title: 'Phantom Blade Zero',
    developer: 'S-Game',
    publisher: 'S-Game',
    platforms: ['PC', 'PS5'],
    genre: 'Action',
    releaseDate: '2026-10-29',
    status: 'upcoming',
    summary: '29 oktober 2026 op PS5 en pc.',
    coverLabel: 'PBZ',
    related: [{ collection: 'news', slug: 'oktober-is-dichtbij' }],
    seo: {
      title: 'Phantom Blade Zero kalender',
      description: 'Gedateerde release 29 oktober 2026.',
    },
  },
  {
    slug: 'zelda-ocarina-of-time-switch-2',
    title: 'The Legend of Zelda: Ocarina of Time',
    developer: 'Nintendo',
    publisher: 'Nintendo',
    platforms: ['Switch 2'],
    genre: 'Avontuur',
    releaseDate: '2026-11-05',
    status: 'upcoming',
    summary: 'Ocarina of Time op Switch 2, 5 november 2026.',
    coverLabel: 'OOT',
    related: [{ collection: 'news', slug: 'ocarina-krijgt-een-dag' }],
    seo: {
      title: 'Zelda Ocarina of Time Switch 2 kalender',
      description: 'Gedateerde release 5 november 2026 op Switch 2.',
    },
  },
  {
    slug: 'grand-theft-auto-vi',
    title: 'Grand Theft Auto VI',
    developer: 'Rockstar Games',
    publisher: 'Take Two',
    platforms: ['PS5', 'Xbox'],
    genre: 'Action',
    releaseDate: '2026-11-19',
    status: 'upcoming',
    summary: 'Officieel 19 november 2026, PS5 en Xbox Series. Geen review tot de build er is.',
    coverLabel: 'GTA',
    coverImage: '/covers/grand-theft-auto-vi.jpg',
    related: [{ collection: 'news', slug: 'gta-vi-blijft-19-november' }],
    seo: {
      title: 'GTA VI kalender',
      description: 'Grand Theft Auto VI: 19 november 2026, PS5 en Xbox Series.',
    },
  },
  {
    slug: 'dragon-quest-monsters-withered-world',
    title: 'Dragon Quest Monsters: The Withered World',
    developer: 'Square Enix',
    publisher: 'Square Enix',
    platforms: ['PS5', 'Switch', 'Switch 2'],
    genre: 'RPG',
    releaseDate: '2026-12-03',
    status: 'upcoming',
    summary: '3 december 2026 op PS5 en Switch families.',
    coverLabel: 'DQM',
    related: [],
    seo: {
      title: 'Dragon Quest Monsters The Withered World kalender',
      description: 'Gedateerde release 3 december 2026.',
    },
  },
  {
    slug: 'monster-hunter-wilds-switch-2',
    title: 'Monster Hunter Wilds',
    developer: 'Capcom',
    publisher: 'Capcom',
    platforms: ['Switch 2'],
    genre: 'Action',
    releaseDate: '2026-12-04',
    status: 'upcoming',
    summary: 'Switch 2 versie, 4 december 2026. Gedateerd.',
    coverLabel: 'MHW',
    related: [],
    seo: {
      title: 'Monster Hunter Wilds Switch 2 kalender',
      description: 'Gedateerde Switch 2 release 4 december 2026.',
    },
  },
  {
    slug: 'professor-layton-new-world-of-steam',
    title: 'Professor Layton and the New World of Steam',
    developer: 'Level 5',
    publisher: 'Level 5',
    platforms: ['PC', 'PS5', 'Switch', 'Switch 2'],
    genre: 'Puzzel',
    releaseDate: '2026-12-10',
    status: 'upcoming',
    summary: '10 december 2026. Gedateerd op de lijst.',
    coverLabel: 'LAY',
    related: [],
    seo: {
      title: 'Professor Layton New World of Steam kalender',
      description: 'Gedateerde release 10 december 2026.',
    },
  },
  {
    slug: 'path-of-exile-2',
    title: 'Path of Exile 2',
    developer: 'Grinding Gear Games',
    publisher: 'Grinding Gear Games',
    platforms: ['PC', 'PS5', 'Xbox'],
    genre: 'RPG',
    releaseDate: '2026-12-11',
    status: 'upcoming',
    summary: '11 december 2026 op PS5, Xbox Series en pc.',
    coverLabel: 'POE2',
    related: [],
    seo: {
      title: 'Path of Exile 2 kalender',
      description: 'Gedateerde release 11 december 2026.',
    },
  },
]
