import type { NewsArticle } from '@/types/content'

const author = 'Kay van Elsen'

export const newsBatchB: NewsArticle[] = [
  {
    slug: 'interview-insomniac-games-over-wolverine-reviews-openwereldgames-en-de-grote-lek',
    title: 'Interview: Insomniac Games on Wolverine reviews, open worlds and the big leak',
    excerpt:
      'Marvel’s Wolverine lands tomorrow, the next chapter in Insomniac Games’ own Marvel universe. Shortly before release I sat down with Lead Animation Director Brian Wyser, who talked about the reactions, why Wolverine has no open world, and the big Insomniac leak.',
    author,
    publishedAt: '2026-09-14',
    category: 'PlayStation',
    tags: ['PlayStation', 'Marvel', 'Interview'],
    coverLabel: 'WOLV',
    coverImage: '/covers/articles/wolverine-marvel.jpg',
    gameSlug: 'wolverine-marvel',
    related: [
      { collection: 'reviews', slug: 'wolverine-marvel' },
      { collection: 'news', slug: 'review-wolverine-is-een-fantastisch-gemaakte-game-maar-geen-fantastische-game' },
    ],
    seo: {
      title: 'Interview: Insomniac Games on Wolverine reviews, open worlds and the big leak',
      description:
        'Brian Wyser on Wolverine’s linear design, violence, reviews and the 2023 Insomniac leak. Out 15 September on PS5.',
    },
    body: [
      'With five games on PlayStation 5, Insomniac Games is not only one of Sony’s most productive studios, but also one of the most praised. The Marvel’s Spider-Man games in particular land well, thanks to the joy of swinging through an open world and MCU-scale blockbuster action. Ratchet & Clank: Rift Apart also turned heads, especially for its technical feats, and is often compared visually to a Pixar film.',
      'Around Wolverine the conversation has been different for a while, especially since Sony’s decision to stop physical games from 2028. Every social post about the upcoming game came with plenty of venom, and now that the review embargo has lifted the game is still being picked apart. From mirror reflections to fart gas controversy: players seem to have their minds made up before the game is even out.',
      'Reactions. That does cloud the debate around Marvel’s Wolverine, because compared with those hits the game does come up a bit short. Even though I personally am a lot more positive than Simon in his review, we can all agree that Wolverine is simply a lot less ambitious than previous titles, whatever you make of that.',
      'Interestingly, the review embargo lifted just before I spoke with Brian Wyser, who did not say much of substance about the reception so far: “I have looked at the reviews, but honestly I am mainly glad people have been able to play the game. First of all I am proud of the passion my team put into this game, and I appreciate people who have played it and want to share their opinion.”',
      'Insomniac Games often gathers in the studio when a game comes out, mainly to watch reactions during livestreams. “There are moments in these games where the goal is to make you cry or make you angry. If I see that on a viewer’s face while they are playing, that is hugely satisfying for me. That is really all I want: that you feel something.”',
      'Deadly helicopter crashes. As Lead Animation Director, Wyser leads teams of animators, and he was himself responsible for the praised animation in titles such as Spider-Man: Miles Morales and Ratchet & Clank: Rift Apart. For Logan the team faced a new challenge: the feral, vertically limited mutant moves completely differently from Spider-Man, so they had to go back to the source.',
      '“We start with a lot of research: comics, films, TV. We go through everything we can find, looking for a pose or action that sparks something. Then we animate that ourselves, or we take it to the mocap floor and work with our stunt performers, trained martial artists with a lot of different skills. Even on the floor ideas come, from me or from my lead animators, and by working with the stunt performers those ideas evolve into something that feels physically truer and more dynamic.”',
      'Wolverine also makes no concessions on violence, and is therefore a much bloodier game than Spider-Man. For the art directors, who looked at gruesome reference photos of body parts among other things to put them on screen as realistically as possible, that was mainly a challenge. According to Brian they had to “take a break now and then”, but at least they did not take the horrific images home, as was the case with some Mortal Kombat makers. He himself found it hardest to watch helicopter crashes for Miles Morales.',
      '“For that game I spent an evening getting that helicopter animated correctly, which meant I watched helicopter crashes on YouTube for about an hour. I did not feel good about that, because I knew some of them had fatal casualties. It is not for everyone, and I do not glorify it and I am not excited about it, but it is what is honest for the character. He is a man with claws on his hands, roughly half a metre long. To do him justice in a fight, there really would be a lot of blood.”',
      'No open world. One of the biggest flashpoints around Wolverine is clearly the structure. Where some people had expected an open world game, this is the opposite: a very linear rollercoaster with little room to explore. I was mainly curious whether Insomniac sees that as an advantage, in a crowded game year where the biggest title is also a gigantic open world game.',
      '“That may be so, but honestly when we approach a game we always look at what is right for the character,” he explains. “In this case an open world just was not right for Wolverine. He is not that type of hero, based on the stories we all know. To really hit Wolverine’s DNA, it would not be right to tell an open world story in which he is the protector of a certain area. That is not how he works.”',
      'He also stresses that a non-open-world game does not translate into less development time or less work. The studio spent around five years on the game, with the lion’s share of that time in iterating the gameplay. It helps, according to Wyser, that, as Final Fantasy 7 Revelation director Naoki Hamaguchi also said earlier, development teams stay together, or at least stay inside the studio. That is how Insomniac Games shipped Marvel’s Spider-Man Remastered, Miles Morales, Ratchet & Clank: Rift Apart, Spider-Man 2 and now Wolverine on one console generation. Given current conditions, that is a serious achievement.',
      'To close I still ask, carefully, about the hack during Wolverine’s development in 2023. Not only did gameplay and the full plot of the game leak, personal data and all upcoming Insomniac Games projects leaked too.',
      '“The only thing I can say about it is that I am really impressed by how our team grew closer through that experience, our support team, our IT, and how everyone got through that event. And speaking for myself as a developer, I was relatively able to keep going with my team. That is what I would say about it. It did not really change what we were doing. It is something that made us grow closer as a group.”',
      'Marvel’s Wolverine comes out on 15 September for PlayStation 5.',
      'What does Marvel’s Wolverine cost in the Netherlands? On 14 September 2026 Marvel’s Wolverine sits in the Dutch PlayStation Store at 79.99 euro as a digital Standard Edition. The Digital Deluxe Edition costs 89.99 euro and the separate Digital Deluxe upgrade is listed at 10.00 euro. Physical shop prices can sit lower, but the official digital price matters most for players without a disc drive.',
      'Which console do you need for Marvel’s Wolverine? Marvel’s Wolverine is a PlayStation 5 game and is listed in the Dutch PlayStation Store as a PS5 title with PS5 Pro Enhanced support. That means you can play it on a regular PS5, while a PS5 Pro can offer extra visual improvements. There is no PS4 version listed and no Dutch PC or Xbox release announced.',
      'How suitable is Marvel’s Wolverine for young players? Marvel’s Wolverine is aimed at adult players. Dutch shops list a PEGI 18 rating and the American ESRB gives the game Mature 17+ for blood, intense violence, strong language and other adult themes. Because of the explicit fights and bloody presentation this is not a logical choice for young children, even if it is a well known Marvel hero.',
      'What is the difference between Marvel’s Wolverine and Marvel’s Spider-Man? Marvel’s Wolverine turns on direct, violent action with Logan as a rough fighter, while Marvel’s Spider-Man is mainly known for open world exploration and smooth swinging through New York. The biggest difference is therefore pace and structure: Spider-Man feels freer and lighter, Wolverine more compact and harder. If you mainly want to cross a big city, Spider-Man is the better fit.',
      'Which edition of Marvel’s Wolverine should you pick? For most players the Standard Edition of Marvel’s Wolverine is the safest choice, because it contains the full game. The Digital Deluxe Edition adds extra outfits, claws, tech points and PlayStation avatars. Only pick the more expensive version if cosmetic extras matter to you or you want more variety immediately. The gameplay base stays the same in both editions.',
    ],
  },
  {
    slug: 'gespeeld-final-fantasy-resonance-voelt-als-een-warm-dekentje',
    title: 'Played: Final Fantasy Resonance feels like a warm blanket',
    excerpt:
      'HD-2D graphics once made the dream of classic JRPG fans come true. Old Dragon Quest games returned first with polished pixel art, a tone Square Enix continued with Octopath Traveler. Now Final Fantasy is on the edge of that HD-2D world, and Resonance goes back to basics. After a long Gamescom session and hours with the demo, we only want more.',
    author,
    publishedAt: '2026-09-13',
    category: 'PlayStation',
    tags: ['PlayStation', 'Final Fantasy', 'Preview'],
    coverLabel: 'FFR',
    coverImage: '/covers/articles/final-fantasy-resonance.jpg',
    gameSlug: 'final-fantasy-resonance',
    related: [
      { collection: 'news', slug: 'gespeeld-final-fantasy-7-revelation-wordt-de-afronding-van-een-legendarische-trilogie' },
      { collection: 'news', slug: 'square-enix-wil-fysieke-games-blijven-maken-ondanks-dat-sony-ermee-stopt' },
    ],
    seo: {
      title: 'Played: Final Fantasy Resonance feels like a warm blanket',
      description:
        'Hands-on with Square Enix’s HD-2D Final Fantasy Resonance. Out 22 October on consoles, PC and Switch.',
    },
    body: [
      'You might ask: why? How can it be that Square Enix is only now bringing Final Fantasy into the HD-2D stable. I mean, that the visual style works has been obvious for a long time. Maybe it has to do with the base of Final Fantasy Resonance. The game is loosely based on the first chapter of Final Fantasy Brave Exvius, a mobile game that launched well over ten years ago and has not been playable for a couple of years.',
      'Square rebuilt the game almost from the ground up, stripped out all microtransactions and designed a more focused story. The end result should keep us busy for dozens of hours, and judging by my first hours with the game, that will succeed twice over. The story setup is fairly simple: a few evil guests, a kind of knights in shining armour, but bad. They threaten a set of powerful crystals that supply the world with energy. It is up to you and your party to stop that.',
      'Stagger as if your life depends on it. The narrative therefore fits Final Fantasy Resonance like a glove, and that is true of almost everything in the game. From simple effects such as wind through grass and hair, light through stained glass, to rolling water, everything lands perfectly in Square Enix’s HD-2D engine. The mix of pixel art and 3D environments clicks beautifully and turns the Grandshelt Isles into a world you want to stay in. Add the fabulous music and tasty voice acting, and you have a highly attractive package that keeps impressing.',
      'At Gamescom I was given an isolated slice of gameplay, a dungeon built around the wind element. Unlike last year I did not have a bursting schedule during the show, and I enjoyed that fully during the session. I could sit for a good hour and a half in Square’s booth to beat the end boss, and I needed that time. The segment sits a bit later in the game, because the party already has five or six people. Fighting power I need in the dungeon, where danger waits around every corner.',
      'Series players already know what to expect from the turn based combat: find your opponent’s weaknesses and exploit them fully. With Resonance, Square also implements the stagger mechanic you know from later games. It comes as a bar you empty with attacks. Once empty, the enemy is open for extra fat damage and also cannot attack for a turn. So you want to throw all attack power at those moments, especially because you also earn extra turns after a stagger and thereby prevent an extra strong attack from the opponent.',
      'Who may attack when is shown on a bar at the top of the screen. There are characters with a baton pass skill, so you can give turns to characters who happen to be useful in that fight. It is one of many examples that facilitate the player’s tactical brain, and when a strategy lands it feels extra good. The end boss I beat after a long grind at Gamescom also has a fun story hook, it turns out after the fight. He is not who you think he is, but who exactly I am of course not going to spoil.',
      'A set of familiar faces. Maybe the most gripping hook in Resonance’s combat is the Visions. They are essentially memories of the franchise’s great heroes, who also fight at your side. Each party member can have one Vision behind them, and they also have separate roles that fit extra well with a party member. Think Cloud Strife, Tidus or the Onion Knight. In Brave Exvius, Visions were one of the gacha elements; players could buy them for real money. There were hundreds of Visions available, but in Resonance that number is cut back to a manageable roster to choose from.',
      'During my Gamescom session I had heroes such as Noctis, Cloud and Tidus on the team, but the demo you can now download in various digital stores limits that number to around five. In the demo I unlocked Cloud, the Warrior of Light, Terra, White Mage and Black Mage. There are also teasers pointing at big baddie Sephiroth as a Vision, but the developer will say absolutely nothing about that. So that is still wait and see. I think Visions are the element first hour fans will go wild for. They of course have signature attacks, so Cloud can use Cross Slash and Climhazzard. All Visions can also be strengthened separately, which only adds depth.',
      'The biggest attacks all come with animations series fans will love. They range from a CGI animation to a fully HD-2D rendered finishing blow, with all the splendour that implies. Of course the individual party members also have their own super moves, called Resonance attacks, which are shown beautifully. The condition for those manoeuvres is that you stagger the opponent’s entire playfield, so every enemy has to be smashed before you can go Resonance for the finishing blow.',
      'Unquenchable Final Fantasy hunger. Because Gamescom was mainly tasting and learning in Final Fantasy Resonance, the recent arrival of the demo was a fine reason to dive in fully. I took my three person party to the maximum available level 15 and all available Visions to their maximum of level 5. I beat every possible enemy, including the strongest level 20 spider, and it took me around six hours to see everything. Because demo progress carries into the full game, there is also a motive to squeeze the demo dry.',
      'So I am left enthusiastic, hungry for more Final Fantasy Resonance. Anyone afraid this is a lazy remake of a mobile gacha game: stop your scepticism. Next month this becomes a full JRPG you can potentially lose yourself in. For someone who never played the original, it is of course still wait and see how all characters will develop. Because Resonance only borrows parts of Brave Exvius, it is also still to be seen which surprises wait for first hour players. What is clear is that HD-2D fans have another game to look forward to.',
      'Final Fantasy Resonance comes out on 22 October for PlayStation 5, Xbox Series X and S, PC, Nintendo Switch and Nintendo Switch 2.',
      'What is the difference between Final Fantasy Resonance and Brave Exvius? Final Fantasy Resonance is a rebuilt console and PC game, while Final Fantasy Brave Exvius was originally a mobile game with gacha elements. Resonance uses parts of the story and familiar heroes as a base, but pulls microtransactions out of the core experience. That makes it feel more like a traditional premium JRPG with fixed progress, turn based battles and a bounded campaign.',
      'How much does Final Fantasy Resonance cost in the Netherlands? In the Netherlands Final Fantasy Resonance is listed digitally at 59.99 euro for the standard edition on the PlayStation Store. The Digital Deluxe Edition costs 69.99 euro there. Physical versions at Dutch shops can differ per platform and stock. Always check the shop page just before buying, because preorder bonuses, shipping and temporary deals can change the best choice.',
      'How long does a classic JRPG like Final Fantasy Resonance take? A classic JRPG often asks for dozens of hours, especially if besides the main story you also want to deepen characters, gear and optional fights. The Final Fantasy Resonance demo can already last several hours if you unlock and max everything. So do not count on a short in-between for the full game, but on an adventure for longer play sessions.',
      'Why is HD-2D popular with JRPG fans? HD-2D works because it combines pixel art with modern lighting, depth and camera work. The familiar charm of 16-bit RPGs stays intact, while environments look more dynamic and richer. For JRPG fans that feels familiar without becoming old fashioned. Worlds with crystals, airships, dungeons and turn based battles especially benefit from that mix of nostalgia and modern presentation.',
      'Which Final Fantasy should you play if you are new to the series? New players usually do not have to start at part 1, because many Final Fantasy games tell standalone stories. If you want classic turn based battles, look at pixel remasters or HD-2D style projects such as Resonance. If you want modern action, you land more on recent mainline games or remakes. So pick on play style: tactical and nostalgic, or cinematic and faster.',
    ],
  },
  {
    slug: 'blizzard-bevestigt-eindelijk-een-nieuwe-starcraft-game-maar-je-moet-er-nog-jaren-op-wachten',
    title: 'Blizzard finally confirms a new StarCraft game, but you will wait years',
    excerpt:
      'BlizzCon, the event built around Blizzard Entertainment’s games and universes, has kicked off. The company immediately makes a few heavy announcements, including a new StarCraft game and Diablo 5. The catch: these games are still years away.',
    author,
    publishedAt: '2026-09-13',
    category: 'Xbox',
    tags: ['Xbox', 'Blizzard', 'Industry'],
    coverLabel: 'SC',
    coverImage: '/covers/articles/starcraft.jpg',
    related: [
      { collection: 'news', slug: 'hideo-kojimas-physint-wordt-nu-gemaakt-met-xbox-nadat-playstation-zich-heeft-teruggetrokken' },
    ],
    seo: {
      title: 'Blizzard finally confirms a new StarCraft game, but you will wait years',
      description:
        'BlizzCon 2026 confirms a story driven StarCraft open world for 2030 and Diablo 5 for 2029.',
    },
    body: [
      'Those announcements and more were made during the BlizzCon 2026 Opening Ceremony, where first of all the StarCraft shooter rumours have been circling for a while was confirmed. That was done with a trailer that contains no footage, but the announcement confirms the game is a story driven open world game. So it is a very different beast from the earlier two StarCraft titles, both RTS (real time strategy) games. Strikingly, the plan is to release the game in 2030, but more on that window later.',
      'A new Diablo game. StarCraft is not the only Blizzard franchise getting a new entry: the fantasy role playing series Diablo also continues with Diablo 5. The short teaser already shows some of the dark world where, most likely, it is again up to the player to put the monsters down. Although a new Diablo 4 update was also announced immediately, adding Amazon warriors as a playable class, Diablo 5 also has a release window: 2029.',
      'Why are these games announced so early? For fans these announcements are bound to excite, but there is a logical question to ask. Why announce these games so early? We have known for years that game development can take a long time, but announcing games that only arrive in three or four years is not all that common. In fact, some publishers prefer to put the announcement closer to release. Look at Nintendo, with Metroid Ravenous and Kirby and the World Beyond. There is not even a year between announcement and the expected release date of those titles.',
      'But the answer is also a bit obvious. Blizzard is not Nintendo. In fact, Blizzard Entertainment is now part of Xbox Game Studios, a fact that puts this choice in much better perspective. Microsoft’s purchase of Activision Blizzard was one of the largest media takeovers ever, with a total of around 75 billion dollars that the Xbox owner paid for the whole operation. That gave Xbox the publishing rights to beloved franchises such as Call of Duty and the entire catalogue of Blizzard brands, including Diablo and StarCraft.',
      'Xbox Game Studios went through a drastic change earlier this year, with a new CEO in Asha Sharma, who has to get the Xbox operation back on track. In July it became clear that a heavy round of layoffs was part of that, with the closure and/or spin-off of five former Xbox studios. Later it became clear that part of the changes inside Xbox is also a renewed focus on existing, large IP. Multiple new Fallout projects are being worked on, alongside The Elder Scrolls 6.',
      'All these developments are puzzle pieces that make announcing the StarCraft shooter and Diablo 5 this early a bit more logical. Blizzard, and Xbox in particular, is showing it is investing in the franchises players know and love. Besides the new game announcements, content updates were also announced, such as Diablo 4’s, but the hero shooter Overwatch is still getting updates too. Is there still a PvE mode in there, Blizzard?',
      'Xbox is also visibly expanding into wider entertainment, with the announcement of a Diablo television series, produced with Netflix, which also came by during the BlizzCon opening ceremony, with a matching note to watch for similar announcements around Overwatch and StarCraft.',
      '2029 and 2030 are nonetheless still far away, and under previous leadership Xbox cancelled several ambitious projects, some based on known IP such as Perfect Dark, but the studio seems to want to invest strongly in the future. Also given that earlier this week it announced the collaboration with Kojima Productions to produce Physint, after PlayStation walked away from that project. About his upcoming spy game, Hideo Kojima has also said earlier that the release is still years away.',
      'What is the difference between StarCraft and Diablo? StarCraft is about real time strategy, where you build bases, manage resources and command armies. Diablo is an action RPG in which you make one character stronger with skills, loot and gear. That is why StarCraft especially speaks to players who like tactical overview, while Diablo leans more on direct fights, loot and character growth. Both series do share Blizzard’s emphasis on recognisable worlds and long community support.',
      'How can you play the existing StarCraft games now? StarCraft II is partly free to play on PC, including large parts of the single player and multiplayer. The original StarCraft and the multiplayer parts of StarCraft II are free, while StarCraft: Remastered and the StarCraft II: Campaign Collection can be played through PC Game Pass or Game Pass Ultimate. For PC players that runs via Battle.net, sometimes combined with the Xbox app.',
      'Which Blizzard games are on Game Pass in the Netherlands? In the Netherlands Diablo IV is available through Game Pass on Xbox and PC, depending on your subscription and platform. For StarCraft, StarCraft: Remastered and the StarCraft II: Campaign Collection are available on PC via PC Game Pass or Game Pass Ultimate. The Game Pass catalogue changes regularly per region, platform and subscription type, so always check the live library in the Xbox app before installing.',
      'Why do studios sometimes announce games years before release? An announcement three or four years before release can help win trust with fans, investors and staff. Big games often have long production tracks, especially if a new engine, open world or different genre is involved. At the same time it is risky: expectations rise quickly and plans can change. That is why some publishers prefer shorter campaigns just before launch.',
      'What did the Microsoft takeover mean for Blizzard? Microsoft completed the Activision Blizzard takeover on 13 October 2023. Since then Blizzard sits under Microsoft Gaming and the Xbox organisation. That does not automatically mean every Blizzard game becomes Xbox exclusive, but it does change the strategy around Game Pass, platform choices and investment in known brands. Franchises such as Diablo, StarCraft, Overwatch and World of Warcraft have therefore become more important inside Xbox’s broader portfolio.',
    ],
  }
]
