import type { NewsArticle } from '@/types/content'

const author = 'Kay van Elsen'

export const newsBatchD: NewsArticle[] = [
  {
    slug: 'review-wolverine-is-een-fantastisch-gemaakte-game-maar-geen-fantastische-game',
    title: 'Review: Wolverine is a fantastically made game, but not a fantastic game',
    excerpt:
      'Normally Wolverine should have been a slam dunk. Sony’s own games are almost standardly scored highly, the public swallows them like candy, superhero games are almost always a bullseye these days and developer Insomniac has a reputation of years of nothing but hits. Past results offer no guarantees. Wolverine is anything but a fantastic game.',
    author,
    publishedAt: '2026-09-10',
    category: 'PlayStation',
    tags: ['PlayStation', 'Marvel', 'Review'],
    coverLabel: 'WOLV',
    coverImage: '/covers/articles/wolverine-marvel.jpg',
    gameSlug: 'wolverine-marvel',
    related: [
      { collection: 'reviews', slug: 'wolverine-marvel' },
      { collection: 'news', slug: 'interview-insomniac-games-over-wolverine-reviews-openwereldgames-en-de-grote-lek' },
    ],
    seo: {
      title: 'Review: Wolverine is a fantastically made game, but not a fantastic game',
      description:
        'Marvel’s Wolverine scores 6.8: near technical perfection and great acting, thin gameplay. Out 15 September on PS5.',
    },
    body: [
      'Score: 6.8 out of 10. Plus: technically almost perfect; a cool story with excellent acting. Minus: mediocre gameplay; barely any enemy variety; terrible pacing.',
      'Wolverine is a decent game, but never more than that. Top notch graphics and acting lift it a little above the average, but we are talking about a game, and in this medium those things are secondary. What it actually turns on, the gameplay, is missing the sauce and the salt to get close to what we are used to from Insomniac.',
      'It is quite imaginable that a less hardcore game audience will have a perfectly fine time with the icon who is hairy down to his lower back. Wolverine is one of the most popular superheroes and the actually cool story you walk through here is packed with tight performances. Liam McIntyre deserves the biggest applause, not because he stands head and shoulders above the rest, but because he steps out of the shadow of Hugh Jackman (forever the only real Wolverine). Troy Baker puts down a handsome Essex and Krizia Bajos is probably my favourite version of Jean Grey ever.',
      'Technical perfection. Technically it is also mouth watering until you drown in it. You do not make a game this pretty unless you put one of the best studios in the world to work for years with an almost infinite budget. Not an ugly unfinished corner to be found, not a framedrop in sight, and the way Wolverine comes out of a fight with half torn flesh, his adamantium ribs sometimes fully in view, is a feat.',
      'And all that splendour is not limited to the linear levels. In larger, detailed environments such as Japan or fictional Madripoor, not a stone or leaf is left untreated. The coat this game wears is as clean as it gets, even when soaked in flying blood. With a critical eye you could still say it is too clean: a slightly more distinct art direction would not have been out of place. Over time that handsome face even becomes a bit boring. At least consistent, because that stamp can also be put on the gameplay.',
      'Leave the wheel alone. The positive presentation aside, in the end it is little more than garnish to disguise a simple button masher of a 2004 action game as something of this time. By the time the credits hit, in around ten hours you have mashed square about 10,000 times, and triangle 5,000 times. The first for normal attacks, the second to leap at one of the many enemies. Those enemies consist 90 percent of the time of either soldiers or soldiers in a ninja costume. That dumb mashing is still dutifully alternated with blocking or dodging, but those mechanics live or die by the feeling those actions deliver.',
      'The odd thing is that Insomniac never had to reinvent this wheel. Pretty much every action game, from Bayonetta to Metal Gear Rising and Sekiro, or modern colleagues such as the just released Onimusha, have worked this trick out to perfection. Wolverine learns nothing from it. Dodging never feels like more than a bit of dopey rolling away, while the weird timing of the parry only rarely delivers anything satisfying.',
      'Fine. There are large stretches where the game gets away with brainless mashing. Do not get me wrong, the game is not bad. The more casual gamer probably has less experience with similar games that execute almost everything here many times better. But anyone who knows the genre regularly sees “brainless entertainment” turn into simply “brainless”. It does not help that the game constantly hits the brakes. Because it wants you to walk slowly for the story. Because it wants you to look for drawings for a young mutant. Because it worries itself again about character growth instead of simply being a fun game. We are used to Insomniac mastering both.',
      'Normally it is easy to score a game like this much more harshly, and anyone who believes “gameplay is king” should stay well away. But Wolverine saves a lot with its journey and attention to detail. The storyline that combines Indiana Jones with the X-Men stays tightly upright, a handful of unique scenes steal the show, and despite the simple gameplay I always wanted to see the next chapter. Added up that delivers a decent ride. Over the top of it lies a thought that will not be shaken off: this would have been a better comic, film or series than a game.',
      'Marvel’s Wolverine comes out on 15 September for PlayStation 5.',
      'What kind of game is Marvel’s Wolverine? A single player action adventure for PlayStation 5, built around fast close combat, story missions and Logan’s violent fighting style. Do not expect an open world sandbox, but a focused superhero action game with cinematic scenes and a lot of melee.',
      'How much does Marvel’s Wolverine cost on PS5? The standard edition has a European recommended price of 79.99 euro. Digital extras or fancier editions can cost more. For most players the standard edition is enough because it contains the full game.',
      'How does it compare with Marvel’s Spider-Man? Both come from Insomniac, but they aim at a different feeling. Spider-Man turns on acrobatics, web swinging and open city exploration. Wolverine leans on brute close combat and a darker tone.',
      'Why is it not meant for young children? The violence, blood and hard tone aim at an older audience. The European PEGI rating is 18. That fits the character, but makes it a poor family superhero pick. Parents should look at footage and the age rating first.',
    ],
  },
  {
    slug: 'gespeeld-final-fantasy-7-revelation-wordt-de-afronding-van-een-legendarische-trilogie',
    title: 'Played: Final Fantasy 7 Revelation will close a legendary trilogy',
    excerpt:
      'A little over ten years ago the remake of Final Fantasy 7 still felt like a dream. The legendary role playing game is not merely being made again, it grew into an unimaginably large project. Now that Revelation closes the trilogy, we can cautiously say it will become the best remake ever.',
    author,
    publishedAt: '2026-09-10',
    category: 'PlayStation',
    tags: ['PlayStation', 'Final Fantasy', 'Preview'],
    coverLabel: 'FF7',
    coverImage: '/covers/articles/final-fantasy-7-revelation.jpg',
    related: [
      { collection: 'news', slug: 'square-enix-wil-fysieke-games-blijven-maken-ondanks-dat-sony-ermee-stopt' },
      { collection: 'news', slug: 'gespeeld-final-fantasy-resonance-voelt-als-een-warm-dekentje' },
    ],
    seo: {
      title: 'Played: Final Fantasy 7 Revelation will close a legendary trilogy',
      description:
        'Gamescom hands-on with Final Fantasy 7 Revelation. Highwind, FITS roles, Wutai. Out 8 April 2027.',
    },
    body: [
      'I do have to put a large asterisk on that. Final Fantasy 7 Remake, Rebirth and apparently also Revelation change so much about the original story that it rises above the classic remake. There are parallel timelines, characters who return or die, and many more daring adjustments. So far Square Enix has kept fans cleverly satisfied, but everything stands or falls with how the many questions the games raise are answered in the last part.',
      'Without giving too much away, director Naoki Hamaguchi says it is in any case not a sequel to the original game, as some speculated. According to him it becomes more a kind of best of of all Final Fantasy 7 content that has ever appeared, such as Advent Children and Crisis Core. What that exactly means for the grotesque, hopeless ending of the original he does not want to reveal in the surprisingly cool Square Enix booth at Gamescom. One thing is certain: the world we know from both the original and Rebirth has changed a little again.',
      'The same world, but different. At the time of Remake I still had no nostalgia for the original. Only when I started the Switch version did I understand how that seemingly small story about capitalism, war and eco-terrorists made such an impression. The game had an impressive amount of systems and choices, a cinematic approach, and a plot that constantly surprised. Cloud’s misplaced memories, Barret and his daughter, and the death of Aerith still stick with me, all aspects the remake trilogy expands and adjusts.',
      'Rebirth was about discovery: the moment Cloud leaves Midgar and the story really begins. It is still a peculiar yet good open world game, which already gives away almost the entire world. Hamaguchi struggled with that, but found ways to make the world we have now visited twice feel fresh. “The first is the obvious one: we changed a lot about the look. Junon is attacked by Weapon, so you have places where the city is broken. In Gongaga the water has risen and part of it is now underwater.”',
      'That meteor is not just a detail: it gives a Majora’s Mask-like atmosphere. Everywhere you look the celestial body hangs in the sky. Revelation has no countdown clock, but given the vague ending of Final Fantasy 7 and the choices the team makes, the pressure is high. From the Highwind you have a good view of the comet. “The second approach was changing how you explore those areas. In Rebirth that was largely horizontal exploration. By adding verticality, travelling through the air and looking from above, many locations already felt really different.”',
      'That also makes the Gamescom demo a bit overwhelming. Square Enix encourages us not to dive straight into new areas such as Wutai, but to explore with the airship. That goes extremely quickly, and even makes Revelation feel more like the original and many classic RPGs. The idea, according to Hamaguchi, is that it should reduce stress, because you can move everywhere quickly, whether with the ship, a parachute or chocobos.',
      'Finally seeing the complete world from above is a relief for the fan in me, but a lot does come at you. A laundry list of icons and notifications pops up when we land on familiar Gongaga: hints, side missions and a sea of Monster Assessment Instrument notifications. That is also the intention. Hamaguchi says he personally dislikes being dumped in a huge world without information, with a design that says if you find something, that is good. “I think that is quite frightening for a lot of people.”',
      'New fit. After half an hour looking for a lost chocobo, Revelation promises to be full of absurd detours again, I still dive into Wutai. Besides guaranteed action, it is one of the few locations not yet translated to the remake. Enthusiastic ninja Yuffie plays an important role on arrival, clearly having been away from home for a long time. A few familiar heroes are missing, but for people who know the original that should be no surprise.',
      'Arriving in Wutai, important to a subplot around the war with Shinra, comes with fights. One reason this remake trilogy works is the balance between the original’s turn based system and faster modern action. You can still perform basic attacks quickly, but you practically freeze time for special skills and magic. Once you have it down there is actually no RPG that does it better.',
      'The original was already flexible with Materia, Rebirth added Synergy attacks, and Revelation goes further. Thanks to Function Integrated Tactical Suitwear (FITS), characters can take on specific roles as in older parts: attacking Warrior, defending Knight, Black Mage and Summoner who calls Ifrit. Besides a new outfit, it gives a totally different dimension. Yuffie is not limited to Warrior. In our demo eccentric pilot Cid is a Black Mage who can perform spells twice inside a radius. With the large cast, including Vincent Valentine, the possibilities seem endless.',
      'Honesty requires saying Revelation cannot really be captured in a one hour session. I pick up little of the weight of the story, how the world has changed, and whether FITS is really a game changer. There are still a lot of questions about parallel timelines that Revelation has to answer. My biggest fear is that I will still be left with those questions. Luckily I know how the original ends, and that there is an ironclad foundation to close this trilogy.',
      'Hamaguchi, someone who also only played the original as a fan and now leads this gigantic project, mainly feels fulfilment. “It is a legendary game. So loved by so many people, with very high expectations, and I am making a remake of that. I am now working on the last piece, on the climax of that project, and that really gives a feeling of fulfilment.”',
      'Final Fantasy 7 Revelation comes out on 8 April for PlayStation 5, Xbox Series X and S, Nintendo Switch 2 and PC. Also read our piece on why Square Enix wants to keep making physical games.',
      'Which edition should you buy? For most players the standard edition is safest, because you get the full main game. The Trilogy Edition is interesting if you do not yet own Remake Intergrade and Rebirth. Premium editions make more sense if you want the Story Expansion Pass, digital extras or early access.',
      'How much does it cost in the Netherlands? The digital standard edition sits in Dutch stores at 79.99 euro. On Xbox the Trilogy Edition is offered at 94.99 euro, Premium at 109.99 euro and Premium Plus at 119.99 euro. Physical shop prices can differ.',
      'Which earlier games should you play? Start with Final Fantasy VII Remake Intergrade and then Rebirth. Knowledge of the 1997 original is not required, but makes references clearer. Crisis Core and Advent Children are extra for fans.',
      'How do you choose a platform? Pick the one on which you own or want to play the first two parts, because save data can unlock bonus content. PS5 is logical if you already played there. Xbox is attractive for Play Anywhere. Switch 2 is about portability. PC is for adjustable graphics and store choice.',
      'What is in the Story Expansion Pass? Two planned story expansions: one around Sephiroth and one around Vincent and the Turks, planned between winter 2027 and spring 2028. They will also be available separately. Anyone who only wants the main story does not have to buy the pass immediately.',
    ],
  },
  {
    slug: 'square-enix-wil-fysieke-games-blijven-maken-ondanks-dat-sony-ermee-stopt',
    title: 'Square Enix wants to keep making physical games, even as Sony stops',
    excerpt:
      'Square Enix wants to continue producing physical games where possible. That is what Final Fantasy 7 Revelation director Naoki Hamaguchi says in an interview with ID.',
    author,
    publishedAt: '2026-09-10',
    category: 'Industry',
    tags: ['Industry', 'PlayStation', 'Final Fantasy'],
    coverLabel: 'SQEX',
    coverImage: '/covers/articles/final-fantasy-7-revelation.jpg',
    related: [
      { collection: 'news', slug: 'gespeeld-final-fantasy-7-revelation-wordt-de-afronding-van-een-legendarische-trilogie' },
    ],
    seo: {
      title: 'Square Enix wants to keep making physical games, even as Sony stops',
      description:
        'Naoki Hamaguchi says Square Enix will keep physical editions where it can, including FF7 Revelation on disc.',
    },
    body: [
      'Where Sony stops producing physical games for PlayStation consoles from 2028, one of Square Enix’s most prominent directors says the company wants to keep making physical editions. Hamaguchi has, in his own words, fought for it inside the company, which sold 90.1 percent of its games digitally last quarter, and at least wants to defend the culture around physical games.',
      '“I know that when this topic came up earlier, we said there was still a lot of discussion inside the company about whether a disc version even made sense, whether we could even make one, and that we would do our best to make that happen where possible, and I know there are fans who worry about how that will play out,” Hamaguchi says at Gamescom. “I think no outlet has asked about this recently, so I have never answered it either. This is the first time I am making this information public. We looked into whether we can make physical versions. The outcome is that it can, and that we want to.”',
      'Culture. The director, whose game Final Fantasy 7 Revelation also still comes out on disc on 8 April, says he wants to guard physical game culture. “Physical discs are becoming rarer as an environment, and the number of people who want a disc version is falling. That is in a sense a sign of the times, and that is inevitable to a certain extent.” At the same time: “When I meet press and people from the fan community, someone brings a box and asks if I want to sign it, and I find that a really beautiful piece of game culture. I absolutely want to keep that.” He also says he would like a physical version of Kingdom Hearts 4, due late 2027.',
      'Game key cards. The Nintendo Switch 2 version of Final Fantasy 7 Revelation comes on a game key card: a physical card that requires a partial download. Besides digital Switch 2 versions loading faster than full cartridges, Hamaguchi says it is also quality. “I will absolutely not choose to lower the quality of the game to get it onto a disc. I am not going to cut anything out only to fit inside the disc capacity of a specific platform. Quality comes first.” As he sees it now, they will put as much data on the disc as fits, and let the rest download.',
      'He acknowledges fans who buy a box and cannot play everything from the disc. “A certain number of people will react that way, and that is also completely fair. Protecting the culture around the physical version is something I absolutely want to defend, and given the circumstances this seems the best achievable end point. If we can think of something better, we will.”',
      'Sony stops discs despite criticism. Sony is continuing plans to press no new discs for PlayStation consoles from 2028. The most important reason is that producing discs costs money per game, while according to Sony only fifteen percent of games are currently sold physically. It also earns more through the PlayStation Store without a physical shop in between. Games that come out before 2028, such as Final Fantasy 7 Revelation, can still be reprinted.',
      'What is cheaper, physical or digital? That differs per title and moment. Physical games often have shop competition and can become cheaper second hand. Digital games mainly depend on store deals. Anyone buying on price compares both and also looks at resale value.',
      'How do you choose? Choose physical if you want to lend, resell, collect or have boxes on a shelf. Choose digital if convenience weighs heavier. Watch storage, download size and platform rules.',
      'Which PS5 do you need for physical games? A PS5 with a disc drive. The Digital Edition has no disc slot as standard. On some newer models a separately sold disc drive can be used if the model is suitable. Always check the exact model.',
      'What is a Switch 2 game key card? A physical card that gives access to a game, but the data first has to be downloaded. The card then has to stay in the console. It feels partly physical and partly digital. For collectors that is less attractive than a full cartridge.',
      'Why do collectors want physical games? A box, cover, cartridge or disc is more than access to software. It has collectible value, can be signed and stays visible. Control also plays a part: lending and selling is often easier. On modern releases it remains important whether the full game sits on the medium.',
      'How do digital PlayStation returns work? Stricter than many physical purchases. In practice you usually cannot claim a digital game back once you have started downloading or streaming it, except for a defective product. Preorders and unused purchases offer more room.',
    ],
  },
  {
    slug: 'hideo-kojimas-physint-wordt-nu-gemaakt-met-xbox-nadat-playstation-zich-heeft-teruggetrokken',
    title: 'Hideo Kojima’s Physint is now being made with Xbox after PlayStation walked away',
    excerpt:
      'The upcoming spy game Physint from Metal Gear Solid and Death Stranding maker Hideo Kojima was first going to be produced with Sony PlayStation, but after the company stepped away Kojima Productions has teamed up with Xbox.',
    author,
    publishedAt: '2026-09-10',
    category: 'Xbox',
    tags: ['Xbox', 'PlayStation', 'Industry'],
    coverLabel: 'PHYS',
    coverImage: '/covers/articles/physint.jpg',
    related: [
      { collection: 'news', slug: 'blizzard-bevestigt-eindelijk-een-nieuwe-starcraft-game-maar-je-moet-er-nog-jaren-op-wachten' },
    ],
    seo: {
      title: 'Hideo Kojima’s Physint is now being made with Xbox after PlayStation walked away',
      description:
        'PlayStation cancelled Physint in June 2026. Kojima Productions now partners with Xbox on the spy game.',
    },
    body: [
      'That news broke through the X profiles of Kojima, Kojima Productions, PlayStation and Xbox. Kojima wrote: “In mid June this year we received an unexpected message from PlayStation Studios that they were going to cancel the Physint project. Physint is an important project for both me personally and Kojima Productions. Determined to keep the project alive, we have spent the past three months searching non-stop for a new partner.”',
      '“During seeking advice and many negotiations, we found in Xbox a partner with whom our vision for the future matches, and we have decided to team up with them once again. Rest assured that development of Physint, our genre defining action spy game, is still ongoing.”',
      'Why is PlayStation pulling out? Physint was announced in January 2024 as a collaboration between Kojima Productions and PlayStation Studios. They had already worked together on Death Stranding, and Physint would mean a return to the spy genre Kojima grew big on as the creative brain behind Metal Gear Solid. He has described the project as a culmination of his work. It was also being made with Columbia Pictures. The goal: blur the divide between film and video games in visual style, narrative depth, thematic richness and production scale, including cast, acting, fashion and sound.',
      'High price tags. PlayStation and Kojima Productions do not name a specific reason, but it may have to do with production value. Death Stranding 2: On the Beach has gone over the counter around two million times, an estimated take of around 150 million dollars. An average film blockbuster already sits between 100 and 150 million dollars, often more. Game development is not cheap either, even with existing tools such as Guerrilla’s Decima Engine used on Death Stranding.',
      'Perhaps the return on investment was not promising enough to keep supporting Kojima’s passion project. PlayStation Studios has taken heavy losses from a live service focus that is not working out. Concord was taken offline two weeks after release, Marathon from Bungie was no monster success, and Horizon: Hunter’s Gathering has recently been overhauled. Perhaps Physint was too risky despite the prestige of the developer.',
      'Once again a collaboration with Xbox. Xbox and newly appointed CEO Asha Sharma are delighted. This is also not the first time: Kojima Productions’ next game is OD, a horror game also with Xbox Game Studios. Whether Physint becomes Xbox exclusive is unknown, but it is almost certain it will only come out for the next console generation. Production can easily still take five years, if the partner switch does not hit development too hard.',
      'A lot is still unclear, including which engine they will use without Decima, and how essential Columbia Pictures was. Microsoft is apparently talking with various studios to produce projects based on their IPs, and Xbox says the companies are also going in together on film and TV. In the meantime Kojima Productions is not sitting still: work on OD, the animated film Death Stranding: Mosquito, and a live action Death Stranding film with A24 directed by Michael Sarnoski, who recently said pre-production starts in the coming month.',
      'What kind of game is Physint? An upcoming action spy game from Kojima Productions, positioned as a modern return to the spy genre without the Metal Gear name. Official gameplay details and a date are still limited. Kojima sees it as a crossover between cinematic presentation and interactive action.',
      'Which platforms? No definitive list. Xbox is the new partner and publisher since September 2026, but that does not automatically mean Xbox consoles only. Wait for official shop pages before buying.',
      'How does it differ from Metal Gear Solid? They share the spy theme and Kojima. Metal Gear Solid is a Konami series. Physint cannot simply use the same characters, names or storylines. Expect a spiritual successor in tone and ambition.',
      'What does a publisher switch mean? It can change budget, planning, tech and platforms. Sometimes the core stays upright, but contracts and technology have to be looked at again. On a large project that can cost months. A new publisher can also save a project when the original partner drops out.',
      'Why films and series? Games are treated more as entertainment brands. A film or series can make a world or studio better known with an audience that games less. The risk is that projects become more expensive and more complex.',
    ],
  },
  {
    slug: 'had-nintendo-beter-een-direct-kunnen-doen',
    title: 'Should Nintendo have done one Direct instead?',
    excerpt:
      'This week Nintendo broadcast no fewer than two Direct presentations: one around Zelda’s birthday, and a general one. In Bonuslevel, Cody and Jacco react to both, and mainly ask: should this not have been one presentation?',
    author,
    publishedAt: '2026-09-10',
    category: 'Nintendo',
    tags: ['Nintendo', 'Industry', 'Podcast'],
    coverLabel: 'DIR',
    coverImage: '/covers/articles/metroid-ravenous.jpg',
    related: [
      { collection: 'news', slug: 'nintendo-direct-van-september-2026-de-trailers-en-aankondigingen-op-een-rij' },
      { collection: 'news', slug: 'the-legend-of-zelda-ocarina-of-time-remake-komt-op-5-november-naar-switch-2' },
    ],
    seo: {
      title: 'Should Nintendo have done one Direct instead?',
      description:
        'Two Nintendo Directs in one week: Zelda 40 and a general show. Was splitting them a mistake?',
    },
    body: [
      'Anticipation for a Nintendo Direct is always large, sometimes against better judgement. Nintendo sits in a unique position to announce the next load of games and leave the previous platform behind. Ahead of this week’s Directs we still knew remarkably little about next year, except for titles such as Xenoblade Genesis and Pokémon Winds and Waves.',
      'On top of that the company still had to unveil its biggest game of 2026, The Legend of Zelda: Ocarina of Time. So it took the time in a separate presentation to mainly spotlight that game, then make remaining announcements on Wednesday afternoon.',
      'Full, but still empty. The reveal of the remake, and its November date two weeks before GTA 6, landed like a bomb. From the visual style to the improvements: this autumn we will experience one of the best games ever again in modern form. But the feeling also lingered that not all that much was shown regarding the fortieth anniversary. There is a concert series, but no substantial information about the Zelda film or other long awaited games. The general Direct was quite full, but mainly with ports, rereleases and Switch 2 versions of existing games.',
      'Well, Metroid Ravenous and Kirby and the World Beyond made a lot of that good. Metroid as a follow-up to Dread with an apparently new approach, and Kirby as an open world follow-up to Forgotten Land. The titles kick off 2027 together in a positive way for Switch 2 owners.',
      'Even so Nintendo perhaps would have made more of an impression by trimming both presentations and merging them into one convincing Direct. Of course many more parties are involved in planning than only the company itself, and it does not change the line-up, but maybe we would still have liked to see it differently.',
      'What is a Nintendo Direct? A video presentation in which Nintendo shows new games, updates and release dates. Sometimes everything turns on one game or series, sometimes on a broader Switch 2 and Switch line-up. For players they are mainly handy to see what is coming soon and whether a console purchase or preorder is worth it.',
      'Is buying a Switch 2 now wise? Look at three things: the games you really want, support for your existing Switch library, and when new exclusives appear. Switch 2 also plays compatible Switch games, but some titles may not work fully. Judge whether the available and announced line-up fits how you play.',
      'Which Switch games work on Switch 2? Besides Switch 2 games it can play compatible physical and digital Switch games. Nintendo reports that certain titles may not be supported or not be fully compatible. Check compatibility information if in doubt.',
      'What is the difference between a Switch 2 game and a Switch 2 Edition? A Switch 2 game is made or released for the new console. A Switch 2 Edition is an improved version of an existing Switch game, often bundled with an upgrade pack. If you already own the original, you can on selected titles buy an upgrade pack.',
      'Why do Direct dates matter for buying advice? Dates make a Direct concrete: they show when you actually get something. A strong announcement without a date helps less with planning. Count which games arrive within 6 to 12 months and whether those fit your preferences.',
    ],
  },
  {
    slug: 'nintendo-direct-van-september-2026-de-trailers-en-aankondigingen-op-een-rij',
    title: 'Nintendo Direct of September 2026: the trailers and announcements in a row',
    excerpt:
      'Nintendo has broadcast a brand new Direct presentation, full of updates and announcements of upcoming games, including Metroid Ravenous and a Kirby open world game.',
    author,
    publishedAt: '2026-09-09',
    category: 'Nintendo',
    tags: ['Nintendo', 'Metroid', 'Release'],
    coverLabel: 'DIR',
    coverImage: '/covers/articles/metroid-ravenous.jpg',
    related: [
      { collection: 'news', slug: 'the-legend-of-zelda-ocarina-of-time-remake-komt-op-5-november-naar-switch-2' },
      { collection: 'news', slug: 'had-nintendo-beter-een-direct-kunnen-doen' },
      { collection: 'news', slug: 'review-fire-emblem-fortunes-weave-is-eindelijk-voor-iedereen' },
    ],
    seo: {
      title: 'Nintendo Direct of September 2026: the trailers and announcements in a row',
      description:
        'Metroid Ravenous 28 January, Kirby and the World Beyond, plus the rest of Nintendo’s September 2026 Direct.',
    },
    body: [
      'Earlier Nintendo already put the Ocarina of Time remake in the spotlight with its own Direct for the franchise’s fortieth anniversary. The general Direct then offered three quarters of an hour of trailers and announcements from Nintendo and partners. All the news is lined up below.',
      'Metroid Ravenous comes to Switch 2 on 28 January. Nintendo announced a new two dimensional Metroid, subtitle Ravenous, for January 2027. In this follow-up to Dread, Samus is still trying to get home, but is stranded on an alien moon. Mysterious figures seem to work against her. To escape she seems to feed on opponents, absorbing enemies so her appearance becomes more monstrous piece by piece. Smooth platforming is shown again, and in one shot you look over Samus’s shoulder in what may be a third person perspective.',
      'Kirby and the World Beyond announced. Next year Kirby turns 35, and as part of that the open world game comes out. The first trailer shows an idyllic colourful world where Kirby walks and floats, inhaling enemies for their powers. He then finds he is inside a dome, which he breaks with a gigantic sword to reveal an even larger world.',
      'Mario Kart World gets free SNES tracks in VS mode today, inspired by courses from the original Mario Kart. They also use question mark blocks on the ground instead of modern item boxes. Two new Knockout Tour routes were added too.',
      'Monster Hunter Wilds on Switch 2 is dated 4 December, with a new trailer. The Ascendance expansion from the recent State of Play later comes to Switch 2 as well. Wilds already came out in early 2025 for PS5, Xbox Series X and PC. Players hunt monsters with more detail than ever, can carry an extra weapon on their mount, and get a Focus mode to find weak points.',
      'Popular friendslop game Meccha Chameleon comes to Switch 2 today. Friendslop is a catch-all for relatively simple indie games you mostly play with friends. Here you hide by colouring and drawing over yourselves. The Switch 2 version supports crossplay and mouse functionality.',
      'More Nintendo content: the second Pokémon Pokopia Expansion Pack update later in 2026 centres on dressing Ditto and other Pokémon. Hyrule Warriors: Age of Calamity gets a Switch 2 Definitive Edition with all DLC, better performance and Calamity Mode. Star Fox (2026), the remake of Lylat Wars, gets a free update including local split screen Battle Mode for four players.',
      'And the rest of a 45 minute show: Star Fox Adventures on GameCube Nintendo Classics. Pikmin 4 Switch 2 edition on 12 November. Professor Layton and the New World of Steam on 10 December. Silent Hill 2 Remake’s developer announces Onyx: The Dark Grip. Disney Dreamlight Valley: The Keepsake Sea in November. Climbing game Cairn in 2027. Resident Evil 2, 3 and 4 new editions on 16 October. Tomb Raider: Legacy of Atlantis also to Switch 2. Nintendo Switch Sports Resort shows free roam on Wuhu Island. Persona 4 Revival on Switch 2 on 20 May, Persona 6 also confirmed. Kingdom Come: Deliverance 2 Royal Edition in 2027. Crisis Core: Final Fantasy 7 Reunion now has a Switch 2 version. A remake of Yo-kai Watch 2: Haunted Domain is on the way. Stage Fright from the Overcooked makers. Xenoblade Chronicles 3 Switch 2 edition includes a Vampire Survivors-like mode. Rhythm game Ondeh Ondeh Kaya’s Tasty Tale. Lego Batman: Legacy of the Dark Knight on Switch 2 on 18 September. Proto Man revealed for Mega Man Dual Override. Eternal Anima looks like a slick top-down RPG. Yu-Gi-Oh! Tag Force GX on 16 February. Fire Emblem: Fortune’s Weave shown once more before release. The Witcher 3 Remastered reconfirmed. Danganronpa 2x2 on 14 January. Fatal Fury: City of the Wolves still this year. Metal Slug Ultimate Collection. Romancing SaGa 3: Destinies United.',
      'What is a Nintendo Direct? An online video presentation sharing new games, updates, trailers and sometimes dates. Some last around 15 minutes, larger general Directs around 45. Nintendo often focuses on its own titles, with room for partners and indies.',
      'Which Switch games work on Switch 2? Nintendo says many physical and digital Switch games play, but not every game works fully the same. Some need an update. There are also free updates and paid upgrade packs for extra content or better performance.',
      'What does Nintendo Switch Online cost in the Netherlands? 19.99 euro per year for an individual standard membership. The Expansion Pack costs 39.99 euro per year. Family yearly subscriptions for up to 8 accounts: 34.99 euro standard and 69.99 euro with Expansion Pack. Check the eShop before buying.',
      'Why do some Nintendo games appear physically later than digitally? Digital needs no production, distribution or shop stock. Physical editions involve cartridges, packaging, logistics and regional stock. Publishers sometimes also test digitally first. Collectors still want physical, but anyone who wants to play immediately often finds digital fastest.',
    ],
  },
]
