import type { NewsArticle } from '@/types/content'

const author = 'Kay van Elsen'

export const newsBatchA: NewsArticle[] = [
  {
    slug: 'review-fire-emblem-fortunes-weave-is-eindelijk-voor-iedereen',
    title: 'Review: Fire Emblem Fortune’s Weave is finally for everyone',
    excerpt:
      'From the sidelines I have always looked a little jealous at Fire Emblem fans and the passion they have for the franchise. Of course they are a bit split. One comes for the tactical combat, another for the story, and since Three Houses a new group has arrived that loves filling free time on a calendar. Fun for them, but Fortune’s Weave was needed to convince a new audience: me.',
    author,
    publishedAt: '2026-09-16',
    category: 'Nintendo',
    tags: ['Nintendo', 'Fire Emblem', 'Review'],
    coverLabel: 'FE',
    coverImage: '/covers/articles/fire-emblem-fortunes-weave.png',
    gameSlug: 'fire-emblem-fortunes-weave',
    related: [
      { collection: 'news', slug: 'nintendo-direct-van-september-2026-de-trailers-en-aankondigingen-op-een-rij' },
    ],
    seo: {
      title: 'Review: Fire Emblem Fortune’s Weave is finally for everyone',
      description:
        'Fortune’s Weave on Switch 2 is the Fire Emblem that finally pulls newcomers in, with a 9.0 score.',
    },
    body: [
      'Score: 9.0 out of 10. Plus: four games in one; perfect onboarding; tactics gameplay at its best. Minus: a slow start.',
      'Conclusion: Fire Emblem Fortune’s Weave is the game that finally brought me on board this long running, excellent tactics series.',
      'Where spin off Fire Emblem Engage was a greatest hits release, Fortune’s Weave is the result of every lesson Nintendo has learned across the whole franchise. There are quite a few of those, because the series is not shy about new paths, mechanics or gameplay experiments. Always built on the tactics foundation Fire Emblem grew big on, of course.',
      'Ancient foundation. In a nutshell Fortune’s Weave still gives you a grid each battle, with your characters and an enemy army waiting. When it is your turn you move your distinct characters (and have them attack, cast spells or use an item). Then the enemy army takes its turn. Simple enough that a child can understand it, and deep enough that an average newcomer might still flinch, especially when a simulation layer is added where every day counts. Before this game I was that player too. Looks cool, but is the on ramp not always a bit too high?',
      'That “simple” idea always came with so much attached. All those characters of mine? Each one deepened with a class, strengths and weaknesses, a long backstory, personal bonds with others on the team, and the overarching tactics layer still has to click in your brain so you make the right calls. Then Three Houses added a calendar where I had to fill hundreds of free days with a million options and just hope I chose well. The fact that the game already lasts around 70 hours was enough to scare me off.',
      'Switching on Switch. So it is not strange that all of this kept me a little outside the door. Until Fortune’s Weave, as I said. This game mixes everything good and deep about the series, while going to extremes to make me comfortable as a newcomer. The introduction to the world maybe even lasts a little too long and barely challenges you in the first hours. But it does let me ease into the bathwater.',
      'The hardest part at first is the choice between storylines, because the game is built as one overarching story with one (self made) lead. In practice you spend 95 percent of the time inside one of the four big storylines of Cai, Theodora, Leida or Dietrich. All four head for the world city Dagsion to try their luck in the Heroic Games, because whoever wins sees their greatest wish come true. Another way it meets the player (and me) halfway: after my choice I am not locked to that storyline. Whenever I want, I switch to another for variety.',
      'Training wheels. After that much too long introduction, the options still start to make my head spin. Do I eat to strengthen social ties, or train in the arena? Outside the city gates countless side missions wait, and I can visit dungeons for more crafting materials and XP. And I can… also go to the theatre? The sauna? Hand out gifts? Put every class on everyone I want? The Three Houses trauma and the choice stress almost paralyse me again. Almost. Because Fortune’s Weave is mainly kind and guiding. “No worries,” the game says. Just go to the inn, and we will fill those free days automatically. We will carry you, levelled up, into the next fight. For beginners that is a perfect option.',
      'It helps me focus on the story (as wide as it is interesting) and on the core: that fantastic tactics gameplay. But as days, months, battles and storylines follow each other, my confidence grows. You know what, this time I do want to fill some free time myself. Only the meals, because I want a better bond with someone I want to recruit. And yes, for those side missions I should head out myself. Before I know it I look back and the game has taken the training wheels off. Or better: I took the training wheels off. But they stayed on as long as I needed them.',
      'Do it! A slightly seasoned Fire Emblem fan will not get much from this review, and that is fine, because that person already knows this is their game. I have to make do with anecdotes from colleagues who are veterans. Their endless enthusiasm gives away that for them this is also Fire Emblem at the peak of its powers. They see deeper nuances I do not even notice. I am already glad I am here, that I am enjoying it, and that I never get overwhelmed.',
      'The hope is that Fortune’s Weave is also that game for others, the one that finally pulls you into this long running series. People who stood on the sidelines for a while but never dared to step in. Because yes, it is a lot. And a trailer for a tactics game does not convince as easily as an iconic kid in a green tunic running through a huge adventurous world with a sword.',
      'But to all those people I say: this is the one. This is the Fire Emblem that pulls us in and does not let go. Those dozens of hours pass like minutes, and before you know it you are not on the sideline for the next title, but a fully fledged tactician on the battlefield. Then you are the one preaching the gospel: try it, believe me, it is not that hard, it is magnificent.',
      'Fire Emblem: Fortune’s Weave comes out on 17 September for Nintendo Switch 2.',
      'What do you need to play Fire Emblem: Fortune’s Weave? You need a Nintendo Switch 2. Nintendo is releasing it as a Switch 2 title, so the original Nintendo Switch, Switch Lite and Switch OLED are not suitable platforms. Anyone who wants to buy the game should first check whether the new console is already in the house or fits the budget.',
      'How suitable is Fire Emblem for players who barely play strategy games? Fire Emblem is learnable if you like thinking slowly and are not scared of turn based battles. You do not need fast reflexes, because every move happens on a grid and you set the pace. For newcomers, guidance matters most: clear tutorials, forgiving difficulty and automatic choices make the on ramp much kinder.',
      'Which Fire Emblem should you buy first? Pick the Fire Emblem that matches your console and your patience for story and tactics. On Switch, Three Houses is still a logical start because of the mix of school life, choices and battles. On Switch 2, Fortune’s Weave is more attractive for new players if you mainly want guidance, comfort and a modern presentation.',
      'Why are Fire Emblem games often so long? Fire Emblem games often last dozens of hours because they combine tactical battles with many characters, relationships and storylines. A battle can easily take 20 to 45 minutes, especially if you play carefully. On top of that come dialogues, side missions, training and choices off the battlefield. The length is not only in main missions, but also in preparation and character building.',
      'Which edition of Fire Emblem: Fortune’s Weave should you buy? For most players the standard edition is the sensible buy, especially if you mainly want to play the game itself. A collector edition is only interesting if extra physical goods matter to you and you are willing to pay more. Always check what is actually in the chosen edition before you buy, because contents and stock can differ per shop.',
    ],
  },
  {
    slug: 'grote-artiesten-teasen-gta-6-soundtrack-alle-namen-op-een-rij',
    title: 'Big artists tease the GTA 6 soundtrack: every name so far',
    excerpt:
      'Several major artists are hinting at involvement in Grand Theft Auto 6, presumably as part of the soundtrack. They are also sharing art that has not been shown before.',
    author,
    publishedAt: '2026-09-16',
    category: 'Industry',
    tags: ['GTA', 'Music', 'PlayStation'],
    coverLabel: 'GTA',
    coverImage: '/covers/articles/grand-theft-auto-vi.jpg',
    gameSlug: 'grand-theft-auto-vi',
    related: [
      { collection: 'news', slug: 'de-eerste-gta-6-stemacteur-is-officieel-bekendgemaakt' },
      { collection: 'news', slug: 'the-legend-of-zelda-ocarina-of-time-remake-komt-op-5-november-naar-switch-2' },
    ],
    seo: {
      title: 'Big artists tease the GTA 6 soundtrack: every name so far',
      description:
        'Travis Scott, Keith Richards, Future and more tease Grand Theft Auto 6 music. Official date 19 November 2026.',
    },
    body: [
      'The teasers appeared yesterday across social platforms such as Instagram and X, and come with (incomplete) artwork. Among the names are major artists: Travis Scott, Keith Richards of The Rolling Stones, Future, Morgan Wallen, PinkPantheress, Metro Boomin, Yung Lean, Rauw Alejandro and CA7RIEL & Paco Amoroso.',
      'Album? While most people stick to tagging developer Rockstar Games, rapper Travis Scott shares a slightly longer message, calling it his “return to game.” He was earlier a skin and artist in Fortnite. He also mentions “J… O. H…,” probably referring to the previously shown Jack of Hearts strip club.',
      'Presumably this is the reveal of a soundtrack album, possibly under Rockstar Games’ own music label, CircoLoco Records.',
      'See all the artists below: Travis Scott; Keith Richards (The Rolling Stones); Future (Label Freebandz); Yung Lean; PinkPantheress; Metro Boomin; Morgan Wallen; CA7RIEL & Paco Amoroso; Rauw Alejandro.',
      'Iconic soundtrack. The Grand Theft Auto games are known for iconic soundtracks of licensed music. Not only was getting real music for video games a lot cheaper than it is now, DMA Design (later Rockstar Games) also sat under BMG Interactive, the games arm of Bertelsmann Music Group, which had access to a wide music catalogue.',
      'The Grand Theft Auto games have different radio stations with specific genres, tied together by DJs and fake ads. Besides big artists, the games are also known for making smaller artists famous, so a spot on the list is a prestige moment for many. Below are all confirmed songs from the official trailers in the game so far:',
      'Love is a Long Road by Tom Petty. Hot Together by The Pointer Sisters. Pop Bottles by Birdman, Lil Wayne. Pound Town by Sexyy Red, Tay Keith. Skrilla by Kodak Black. Let Your Love Flow by The Bellamy Brothers. Love Bites by Def Leppard. People Are People by Depeche Mode. But I Think It\'s a Dream by Captain & Tennille. Cars and Girls by Prefab Sprout. Off the Grid by Chk Chk Chk (!!!) (feat. Meah Pace). Devil Woman by Cliff Richard. Se Me Nota (Agarrame) Prod by B-One by Chimbala, Omega. Against All Odds (Take a Look at Me Now) by Phil Collins. Mine O\' Mine by Aluna, Jayda G. Inner Light by Elderbrook, Bob Moses.',
      'When does GTA 6 come out and on which consoles? GTA 6 is officially planned for 19 November 2026. Rockstar names PlayStation 5 and Xbox Series X and S as the platforms you can preorder. A PC version has not been officially announced. For Dutch players that means the console versions lead on the first release.',
      'What does GTA 6 cost in the Netherlands? In the Dutch PlayStation Store GTA 6 is listed at 79.99 euro as Standard Edition and 99.99 euro as Ultimate Edition. Prices can differ per shop and platform, especially for physical code in box versions. On preorders also watch bonuses and terms, such as temporary GTA+ promotions or digital upgrades.',
      'How does radio work in GTA games? Radio in GTA games works as a set of in game stations with genres, DJs, fictional ads and licensed music. While driving you switch stations, so the soundtrack becomes part of the world. GTA 6 seems to continue that tradition, but the full station list is not official yet.',
      'What does a song in a GTA 6 trailer mean for the soundtrack? A song in a GTA 6 trailer does not automatically confirm it will sit on an in game radio station. It does show which music Rockstar is publicly tying to the game. Only when Rockstar officially shares the soundtrack, radio stations or credits is it certain which tracks are available while playing.',
      'Why can music sometimes disappear from older GTA games? Popular music is usually used through time limited licences, so a publisher later has to remove tracks or renegotiate. Rockstar previously changed tracks in GTA IV because of licence limits. That is why game soundtracks do not always stay the same forever, especially on digital versions and updates.',
    ],
  },
  {
    slug: 'militaire-shooter-wardogs-is-een-groot-succes-in-early-access',
    title: 'Military shooter Wardogs is a huge early access hit',
    excerpt:
      'Maybe you picked something up about it in the last few weeks: Wardogs. A few weeks ago there were playtests of the new multiplayer shooter, and the game has now gone into early access. And it turns out Wardogs is a huge success.',
    author,
    publishedAt: '2026-09-15',
    category: 'PC',
    tags: ['PC', 'Shooter', 'Indie'],
    coverLabel: 'WARD',
    coverImage: '/covers/articles/wardogs.jpg',
    related: [
      { collection: 'news', slug: '007-first-light-op-nintendo-switch-2-laat-nog-wat-langer-op-zich-wachten' },
    ],
    seo: {
      title: 'Military shooter Wardogs is a huge early access hit',
      description:
        'Wardogs sold two million copies on Steam in five days, with a 350,000 player peak. Bulkhead and Team17.',
    },
    body: [
      'In the first five days after launch, two million copies of Wardogs flew off Steam’s virtual shelves, with a concurrent player peak of no less than 350,000 players. On day one the game already sold 1.25 million copies, and in the four days after that another 750,000 were added.',
      'Wardogs is made by developer Bulkhead, a studio that earlier shipped titles such as Killrun and The Turing Test. Team17 is the publisher, the same company that has released games such as Hell Let Loose, Overcooked and Dredge.',
      'Why is the game such a success? If you are not fully up to speed on Wardogs yet: the game is a military shooter in which a hundred players are dropped into a gigantic environment based on Eastern Europe and split into three teams. Each team has the same goal: occupy as many Control Zones as possible and be named winner of the match.',
      'The game also has tactical gunplay, mechanics that let you build on the map but also destroy buildings and environments, and a system that lets you buy better and better weapons and gear such as vehicles. Every player starts with ten thousand dollars, and can grow that capital with activities on the map.',
      'Wardogs seems to apply and combine a number of elements from popular shooters such as Battlefield and Counter-Strike. The large environments, the high cost of dying (it takes a while before you come back, and moving across the map costs quite a lot of time) and the destruction you can cause are things Battlefield is known for. The cash mechanics and tactical elements around holding control of different zones then recall Counter-Strike.',
      'I saw many people talking about Wardogs before and after the playtests, so I asked on the IDGames subreddit what people actually think of the game. The replies are mostly positive, with many Battlefield comparisons, but also a few worries about the play style. Apparently it sometimes happens that people camp with snipers, or build a base outside your spawn area to make progress much harder.',
      'Future plans for Wardogs. Because the game is in early access, Wardogs will still grow and be polished in all kinds of ways. Bulkhead has said it wants to stay in Early Access for somewhere between one and two years, so the latest full release is expected somewhere in 2028 at the latest. In that year the developer says it also wants to ship a console version, so people with a PS5, Xbox Series console and maybe even Switch 2 can join.',
      'Until then the studio will work in seasons that add new weapons, vehicles and other kinds of content. Including certain new items will then mean “vaulting” older gear, which means those items are taken out of rotation for a while. The current season will last a month, but Bulkhead CEO Joe Brammer is not yet saying how long future seasons will run.',
      'Many more changes are still coming, such as being able to search for servers by name, and marking favourite servers. Accessibility options for colour blindness, for example, are also on the list.',
      'Wardogs is currently available in early access on Steam for 39.99 euro. Bulkhead has said the final release of Wardogs will be more expensive, to “reflect the more complete experience.” An extra Supporters Pack is available for 12.99 euro and offers a number of cosmetics.',
      'What does early access mean for a game on Steam? Early access means you buy a playable game before the full version is finished. The game can still have bugs, missing features and balance problems. Developers often use this phase to collect player feedback and ship updates. So you are not buying a trial, but also not a finished product with all promised content yet.',
      'Which players get the most out of Wardogs? Wardogs especially suits players who like large online firefights, tactical teamwork and slower movement across large maps. The game is less suitable if you mainly want short matches or fast respawns. With 100 players, three teams, vehicles and Control Zones, Wardogs asks for more patience and team sense than many more compact shooters.',
      'How does a refund work for Wardogs on Steam? For Steam games you can typically request a refund within 14 days of purchase if you have played less than 2 hours. That is useful for an early access game, because performance, servers and balance can still shift. If you play longer, Steam can still review a request, but automatic eligibility is then not guaranteed.',
      'What does Wardogs cost and do you need the Supporter Pack? According to the article Wardogs costs 39.99 euro in early access on Steam. The Supporter Pack costs 12.99 euro and contains cosmetic extras. You do not need that pack to play the game itself. Because Bulkhead says the full release will be more expensive, jumping in early can be cheaper, but only if you find the current state acceptable.',
    ],
  },
  {
    slug: '007-first-light-op-nintendo-switch-2-laat-nog-wat-langer-op-zich-wachten',
    title: '007 First Light on Nintendo Switch 2 waits until March 2027',
    excerpt:
      'The Nintendo Switch 2 version of this year’s James Bond game 007 First Light was still meant to arrive in 2026, but developer IO Interactive has announced it is moving the release to March 2027.',
    author,
    publishedAt: '2026-09-15',
    category: 'Nintendo',
    tags: ['Nintendo', 'Bond', 'Industry'],
    coverLabel: '007',
    coverImage: '/covers/articles/007-first-light.jpg',
    gameSlug: '007-first-light',
    related: [
      { collection: 'reviews', slug: '007-first-light' },
      { collection: 'news', slug: 'grote-artiesten-teasen-gta-6-soundtrack-alle-namen-op-een-rij' },
    ],
    seo: {
      title: '007 First Light on Nintendo Switch 2 waits until March 2027',
      description:
        'IO Interactive delays 007 First Light on Switch 2 to March 2027 to polish performance. Other platforms already shipped.',
    },
    body: [
      'The developer announced that on social channels, including on X. The reason for the delay is that a little more time is needed to fully polish the Switch 2 version of the game.',
      '“To make sure we can deliver an experience with the quality players expect, we have decided to delay the release to March 2027, with the exact date to be communicated later. This extra time goes toward polishing the performance [of 007 First Light] on Nintendo Switch 2.”',
      'The hybrid version of James Bond’s origin story was recently playable at Gamescom in Cologne, and IO says it received positive reactions. So the game is at least not in a bad state on Nintendo’s newest console: the same Gamescom demo will also be playable on the floor at Tokyo Game Show.',
      'For fans who specifically want to play the game on Switch 2, 007 First Light is more than likely worth the wait, going by Dwayne’s review of the PS5 version. He said:',
      '“007 First Light reintroduces James Bond with an ironclad experience: stylish, confident and endlessly exciting through to the credits. At its best it is the ultimate Bond experience, complete with fat gadgets and bombastic action. At the lesser moments it recalls the highly competent Bond shooters EA delivered. IO Interactive is sitting on a mountain of gold that, with the needed refinement, can grow into a fantastic 007 game series. I hope the licence holders give them that chance.”',
      'Why the delay? Of course there are several possible reasons around delaying this Switch 2 version. Shortly after 007 First Light launched it became known that Amazon would have a say in any sequels, and that IO Interactive would have to close new deals for that anyway. Xbox also pulled out of a collaboration with the developer, with whom they were going to develop a fantasy game.',
      'IO has therefore had to lay off staff, but keeps working on “Project Fantasy,” alongside updates for 007 First Light and new missions in the Hitman games the company released earlier. Even so the developer seems to be navigating a tumultuous period.',
      'On top of that, of course, even though Nintendo Switch 2 is many times more powerful than its predecessor, some development time is needed to move a title like this onto hardware that was barely considered, if at all, during the initial development.',
      'Many modern titles do run more than fine on the console: from experience Star Wars Outlaws and Assassin’s Creed: Shadows are absolutely recommendable. And the many announced ports in the latest Nintendo Direct are at least a sign that developers definitely want to use the platform.',
      'Which platforms have 007 First Light? 007 First Light is available for PlayStation 5, Xbox Series X and S and PC via Steam and the Epic Games Store. The Nintendo Switch 2 version sits apart from that earlier release and is delayed to March 2027. For players who do not want to wait, the current console and PC versions are the options.',
      'What does 007 First Light cost in the Netherlands? The standard edition of 007 First Light costs 69.99 euro for PS5 in the Dutch PlayStation Store. The Deluxe Edition has a recommended price of 79.99 euro, though temporary discounts can differ per shop or platform. For the Nintendo Switch 2 version it is wise to wait for the final store page, because price and SKU can differ per platform.',
      'What kind of game is 007 First Light? 007 First Light is a story driven action adventure around a young James Bond. The game is about missions, espionage, gadgets, gunfights and cinematic action scenes, but it is not a direct adaptation of an existing Bond film. IO Interactive developed the game as a new origin story, separate from the film canon.',
      'Why do big games sometimes come to Nintendo Switch 2 later? Big games sometimes arrive later on Nintendo Switch 2 because developers need extra time for optimisation. A hybrid console asks for different choices than a fixed home console or PC, for example around resolution, framerate, battery use and load times. On an action game with many effects, a later release can help make performance more stable.',
    ],
  },
  {
    slug: 'de-eerste-gta-6-stemacteur-is-officieel-bekendgemaakt',
    title: 'A GTA 6 voice actor talks out of school and confirms his role',
    excerpt:
      'We keep learning more about Grand Theft Auto 6 as launch creeps closer. It is easy to forget, but in a game that is meant to be this immersive, actors also play an important part. The first of many actors has now officially confirmed his involvement.',
    author,
    publishedAt: '2026-09-15',
    category: 'Industry',
    tags: ['GTA', 'PlayStation', 'Industry'],
    coverLabel: 'GTA',
    coverImage: '/covers/articles/grand-theft-auto-vi.jpg',
    gameSlug: 'grand-theft-auto-vi',
    related: [
      { collection: 'news', slug: 'grote-artiesten-teasen-gta-6-soundtrack-alle-namen-op-een-rij' },
    ],
    seo: {
      title: 'A GTA 6 voice actor talks out of school and confirms his role',
      description:
        'Stephen Root confirms Brian Heder in Grand Theft Auto 6. Rockstar’s date stays 19 November 2026 on PS5 and Xbox.',
    },
    body: [
      'It is Stephen Root, an actor whose voice you may already have heard in the animated series King of the Hill. In no fewer than 278 episodes he provided voices for several characters, mainly Bill Dauterive and Buck Strickland. He also played Monroe Fuchs in the action series Barry.',
      'In Grand Theft Auto 6 Root plays Brian Heder, as he practically confirms in an interview with Associated Press, the video of which can be watched below. He does not directly say he plays Brian Heder, but he does say his character has been carried along since the marketing kick off last year. The fact that his King of the Hill voice is so well known also quickly makes clear that this is the crime boss.',
      'Who is Brian Heder? What Stephen Root says is right: when we saw the second GTA 6 trailer last year, Heder played a role in it, and he was also included in the list of characters spotlighted on the official website. The character description there reads:',
      '“Brian is a classic drug trafficker from the golden age of smuggling in the [Leonida] Keys. He still trades the product through his shipyard, together with his third wife: Lori. Brian has been around long enough that he now lets others get their hands dirty.”',
      'One of those “others” is Jason Duval, one of the two protagonists of Grand Theft Auto 6, who works for Heder and in return has a house in the Keys.',
      'Going by the Extended Look released a while ago, we can also infer that Brian may play a kind of mentor role for Jason. During a party Brian and Lori throw, Brian takes the young criminal aside and explains that Jason has to decide for himself when it is time to leave that life behind, something I read as a hint toward GTA 6 as a modern western. It is a little striking, given Trailer 2 opens with Jason doing jobs for the crime boss, but who knows how that will go. We will see on 19 November.',
      'Who else is in the GTA 6 cast? Stephen Root is in principle the first actor to confirm his role in the game, though fans have probably already managed to find the voices of Lucia Caminos, the second protagonist, and of Jason himself. It seems Manni L. Perez will take the role of Lucia, an actress who has mostly had supporting parts in various series such as Law and Order. She also voiced a blackjack dealer for GTA Online, so perhaps that put her on Rockstar’s radar.',
      'There is less certainty about Jason, but online speculation suggests Dylan Rourke may take the role. His CV also consists mainly of supporting parts in a few episodes of all kinds of series.',
      'Anyway, the cast of GTA 6 consists of quite a few characters, as you can see in this overview for example. NPCs walking the world are also largely voiced, which also needs voice work. That is an ambitious operation for Rockstar too, but according to the previews an entire branch of the company is practically only busy developing the different figures you meet in Vice City.',
      'There is much more to tell about Grand Theft Auto 6, such as the fact that you can sit in traffic in this video game too, which is why we have this overview and our collection of frequently asked questions. That way you will be fully up to speed on 19 November about what to expect from the game. And if you want to buy the game? You can do that via the blocks below if you like.',
      'When does GTA 6 come out and on which platforms? Grand Theft Auto VI is officially planned for 19 November 2026. Rockstar names PlayStation 5 and Xbox Series X and S as launch platforms. For Dutch players that means you can expect the game on those consoles, as long as you buy through a shop or account region that matches the Netherlands.',
      'Is GTA 6 coming to PC as well? Rockstar has not announced a PC version of Grand Theft Auto VI yet. Official information currently only names PlayStation 5 and Xbox Series X and S. That does not rule out a later PC release, because earlier Rockstar games sometimes arrived later on PC, but for GTA 6 there is no date or confirmation yet.',
      'Which editions of GTA 6 have been announced? For Grand Theft Auto VI a Standard Edition and an Ultimate Edition have been announced. The Standard Edition contains the game itself. The Ultimate Edition adds extra content around Jason and Lucia. Rockstar also says owners of the Standard Edition can later buy an Ultimate Edition Upgrade separately through the digital stores of PlayStation and Microsoft.',
      'How does the physical version of GTA 6 work? According to Rockstar the physical version of Grand Theft Auto VI does not contain a disc, but a download code in the box. You can use that code to download the game digitally. The physical version is due from 12 November 2026 to allow preloading, a week before the planned release on 19 November.',
      'What do we know about the setting of GTA 6? Grand Theft Auto VI is set in Leonida, Rockstar’s fictional version of Florida, with Vice City as an important location. The official description revolves around Jason and Lucia, who after a failed job end up in a larger criminal conspiracy. The setting combines sun, coastal areas, crime and the familiar social chaos of modern GTA worlds.',
      'Why does the GTA 6 cast matter? In a story driven open world game the cast largely decides how believable characters feel. Voice actors do not only deliver dialogue, but often also timing, emotion and character details that make scenes work better. Especially on GTA 6, with Jason, Lucia and several supporting figures, casting can have a lot of influence on the tone of the story.',
    ],
  },
]
