import type { NewsArticle } from '@/types/content'

const author = 'Kay van Elsen'

export const newsBatchC: NewsArticle[] = [
  {
    slug: 'the-legend-of-zelda-ocarina-of-time-remake-komt-op-5-november-naar-switch-2',
    title: 'The Legend of Zelda: Ocarina of Time remake arrives on Switch 2 on 5 November',
    excerpt:
      'During the special Nintendo Direct for The Legend of Zelda’s fortieth birthday, Nintendo showed the first gameplay of the upcoming Ocarina of Time remake. It is also confirmed the game comes out on 5 November, alongside other franchise details.',
    author,
    publishedAt: '2026-09-08',
    category: 'Nintendo',
    tags: ['Nintendo', 'Zelda', 'Release'],
    coverLabel: 'OOT',
    coverImage: '/covers/articles/zelda-ocarina-of-time-switch-2.png',
    gameSlug: 'zelda-ocarina-of-time-switch-2',
    related: [
      { collection: 'news', slug: 'nintendo-direct-van-september-2026-de-trailers-en-aankondigingen-op-een-rij' },
      { collection: 'news', slug: 'had-nintendo-beter-een-direct-kunnen-doen' },
    ],
    seo: {
      title: 'The Legend of Zelda: Ocarina of Time remake arrives on Switch 2 on 5 November',
      description:
        'Nintendo dates the Ocarina of Time remake for 5 November 2026 on Switch 2, with new jumps, items and ocarina mic support.',
    },
    body: [
      'Eiji Aonuma, producer of the series, guided a demo that shows a few early moments from the remake. You see the new visual style, and a number of gameplay related changes are highlighted. Link can now jump with a dedicated button and sprint after he rolls. As in the earlier 3DS remake, the camera can also be turned with the right stick. When you aim a ranged weapon, such as the slingshot in the demo, that can also be done with motion controls.',
      'The menus also seem to have been adjusted, with a Threads of Time tab that shows you different quests and a tapestry that fills in during your adventure. During gameplay itself you can now, as in the modern Breath of the Wild and Tears of the Kingdom titles, switch directly between all your items, through a menu you get by holding R.',
      'The functionality of the important ocarina is also a little expanded. You no longer necessarily have to press the right buttons to play one of the songs, but can hum those tunes, or even play them with your own ocarina, with the sound picked up by the Switch 2 microphone. That is also how the songs are then used in the game.',
      'In general this remake seems to stay fairly faithful to the original game, and mainly make it more playable for a modern audience with certain gameplay changes. And of course a very different look, many times more detailed than the N64 version. When Link arrives in a village you see that all NPCs perform distinct animations, and his blocky tunic clearly contains a lot more detail.',
      'Time was also spent on smartphone features related to this remake. In the Nintendo Switch App you can use the Zelda Notes application to keep statistics from your playthrough, for example, and keep a kind of logbook of your adventure. With points you collect by completing certain tasks in the game, you can unlock songs that can then be played with the ocarina inside the app. It is also possible to make music yourself with the virtual instrument.',
      'How do we feel about the remake? Right after the Direct, Jacco and Cody dove into the recording room to give their opinion. The day after the Zelda Direct there was also a regular presentation full of Nintendo games. That one is also covered at length in the Bonuslevel podcast, but we still wonder a little whether this should not have been one presentation.',
      'Special console and concert series. During the Direct, special Nintendo products with a The Legend of Zelda theme were also revealed. The company is bringing a special edition of the Nintendo Switch 2 with Joy-Con, as well as a matching Pro Controller and carrying case. These products are available from 29 October.',
      'Comparable with the thirty-fifth anniversary, Nintendo is organising various Zelda concerts from next year in honour of the fortieth anniversary. The tour starts in Japan, then goes via the United States to Europe. A concert is planned in London on 3 April, other dates will follow. Ticket prices have not been revealed either.',
      'The 1998 Nintendo 64 game The Legend of Zelda: Ocarina of Time was long seen as the best game ever made, and already got a version on the Nintendo 3DS in 2011. At release the game stood out because it took the Zelda series, which until then was playable in two dimensions, into three dimensions. It also offered a large, lively feeling game world for the time, with diverse regions and timeless puzzles.',
      'Update on the live action film. There was a little more talk about the upcoming live action The Legend of Zelda film during the Direct, but the expected trailer unfortunately stayed away. Shigeru Miyamoto did reconfirm the 30 April release date, and “revealed” that the film will be called The Legend of Zelda. Apparently that was a reveal.',
      'According to Miyamoto there is a reason the film has no subtitle, unlike almost every game in the series. The former developer said during the Direct that the reason behind this decision will become clear when we see the film itself, and that the full Zelda franchise builds toward this story. The film does not follow the story of one of the games.',
      'Already known about the Legend of Zelda film is that Benjamin Evan Ainsworth, who appeared earlier this year in the third season of House of the Dragon, will play Link. Princess Zelda is played by Bo Bragason, known from Renegade Nell and Three Girls. Earlier this year it was also announced that the late actor Sam Neill, Alan Grant in Jurassic Park, also has a role.',
      'The film is directed by Wes Ball, who so far mainly has post-apocalyptic projects behind him. He directed the three Maze Runner films, and his last project was Kingdom of the Planet of the Apes. Sony Pictures is producing the film in collaboration with Nintendo.',
      'What is the difference between Ocarina of Time and Ocarina of Time 3D? Ocarina of Time 3D came out in 2011 for the Nintendo 3DS and was a polished version of the 1998 Nintendo 64 game. The 3DS version added stereoscopic 3D images, an adjusted interface and more comfortable controls among other things. The base stayed the same: the same dungeons, the same time travel setup and the same core of the adventure in Hyrule.',
      'How can you play the original Ocarina of Time on Nintendo Switch? The original Nintendo 64 version is available on Nintendo Switch through Nintendo Switch Online + Expansion Pack. You do not buy the game separately there, but play it as long as your subscription is active. In the Netherlands this pack also gives access to other classic Nintendo 64, Game Boy Advance, Sega Mega Drive and Virtual Boy games inside the Nintendo Switch Online library.',
      'What does Nintendo Switch Online + Expansion Pack cost in the Netherlands? It costs 39.99 euro per year for an individual membership. The family membership costs 69.99 euro per year and can be used by up to 8 Nintendo accounts inside a family group.',
      'Which Zelda game is the best to start with? For new players there are three logical entry points. Ocarina of Time is suitable if you want the classic formula with dungeons, puzzles and time travel. Breath of the Wild feels freer and more modern. Tears of the Kingdom builds on that if you like building, physics and open world systems.',
      'How old is The Legend of Zelda series in 2026? The Legend of Zelda is exactly 40 years old in 2026. The series began in 1986 on the Famicom Disk System in Japan.',
    ],
  },
  {
    slug: 'gespeeld-mega-man-dual-override-is-vooral-heel-toegankelijk',
    title: 'Played: Mega Man Dual Override is mainly very approachable',
    excerpt:
      'Grand Theft Auto 6 will not bother Capcom much. The Japanese developer’s year cannot really go wrong anymore; it has shipped three excellent games so far. Resident Evil Requiem, Pragmata and Onimusha: Way of the Sword did well critically and financially, but what waits in 2027? The Blue Bomber. In Cologne we got a taste of Mega Man Dual Override.',
    author,
    publishedAt: '2026-09-11',
    category: 'PlayStation',
    tags: ['PlayStation', 'Mega Man', 'Preview'],
    coverLabel: 'MM',
    coverImage: '/covers/articles/mega-man-dual-override.jpg',
    related: [
      { collection: 'news', slug: 'nintendo-direct-van-september-2026-de-trailers-en-aankondigingen-op-een-rij' },
    ],
    seo: {
      title: 'Played: Mega Man Dual Override is mainly very approachable',
      description:
        'Hands-on with Mega Man Dual Override at Gamescom. Classic stages, chips as training wheels, Dual Override super form. Spring 2027.',
    },
    body: [
      'I will be honest: I am not that into the classic Mega Man games. My youth was stuffed with spin offs. I took my first steps with Mega Man X on the SNES, a fairly traditional title, but with a much darker version of the character. Later I still played the 3D Legends series on PlayStation. My real love is Mega Man Battle Network, a series that makes the action much more tactical, with a gripping mix of strategy and realtime action.',
      'None of that in the game put in front of me. I was allowed to play through a whole stage, split across three levels. When I leave the Capcom booth after the session, I know: the number may be missing, but this was of course simply Mega Man 12. Capcom knows what it wants with one of its most classic franchises, and that tone simply continues after part eleven. You will again take on around eight robots, then go fist to fist with the real bad guys. In this stage Twinkle Girl is the opponent, and she uses fireworks as a weapon.',
      'Chips as training wheels. Before it is time to take on that Twinkle lady, the Blue Bomber first has to zip through three levels. Before I dive into my first mission, I still get the option to pick loadouts. Here Capcom shows that accessibility sits high on the list. I can equip Mega Man with chips that add a skill to his arsenal. There is a chip that generates a shield that blocks one attack, and a variant that automatically charges strong attacks. Because each level has its own mini boss at the end, that can be a handy boost for newcomers.',
      'The chips sit on top of Mega Man’s existing boss weapon. As usual the hero can use unique attacks from all the big bosses once he beats them. In this case I can use an extra charge attack, where Mega Man gets a temporary form and dashes at enemies. On impact the enemy is launched to the other side of the screen and takes other enemies with him. I cannot spam the attack without risk: on impact Mega Man bounces back, so do it at the wrong moment and he bounces straight into the pit. A handy tool, then, but you still have to think. I mainly see those chips as training wheels, so I go for the classic experience: I can only call the loyal quadruped Rush for a double jump.',
      'Once in the first level I hit my biggest sticking point: the visuals. Levels look too tight and too plastic in every facet, as if I am playing with action figures straight out of the box. A sharp contrast with the rougher, industrial feel I picture for the classic series. Level backgrounds show more than enough depth, but little character. The whole thing lacks expressiveness and therefore feels soulless. Not the Mega Man fans from before part eleven know.',
      'The controls, on the other hand, are tight, precise and extremely responsive. In that sense it clicks, and I do not fear classic Mega Man fans will come up short on gameplay. But those graphics get in my way. That Twinkle lady is putting on a fireworks show in the soulless city I am jumping around, and through all the levels I am treated to all kinds of light effects and particles. Platforms explode under my feet while I try, flying and tumbling, to dodge fireworks. Try, I say, because although foreground and background are clearly separated, it is not always clear to me which fireworks sit in the foreground and can therefore take me out.',
      'Steroids for the Blue Bomber. I hope Twinkle Girl is the only boss with all those light flash effects, because everything I taste of this classic Mega Man does appeal. The first two levels give me all kinds of useful previews of the fireworks misery Twinkle Girl brings. The first area teaches that it is smart to shoot projectiles apart and get closer to the shooter. The next level turns up the pressure with variants where projectiles bounce off walls, and each mini boss shows how projectiles explode into smaller variants that shoot every which way.',
      'Once at Twinkle Girl it becomes clear what the title refers to. Dual Override is that extra strip of power you need to survive, the anabolics (read: steroids) that raise your performance considerably. If Mega Man eats enough damage or deals it, he overwrites all his systems with one button press for a short super form. Normal shots turn into charged shots you fire in bursts, and those deal huge damage. The downside? When you come out of Dual Override, Mega Man is extra weak. He sparks and visibly struggles to stay on his feet. Luckily Twinkle Girl at that point only has two bars left. Beaten, then, without extra chips! Okay, maybe I should try the game next year after all.',
      'Mega Man Dual Override comes out in the spring of next year for PC, PlayStation 4, PlayStation 5, Xbox One, Xbox Series X and S, Nintendo Switch and Nintendo Switch 2.',
      'What kind of game is Mega Man Dual Override? It is a 2D action platformer where you run, jump and shoot through levels full of enemies, projectiles and bosses. The base looks like the classic Mega Man formula: you pick stages, beat robot bosses and then use new attacks. The novelty sits mainly in temporary power boosts and supporting chips, so the game can feel less strict for players who did not grow up with NES-like difficulty.',
      'How hard are classic Mega Man games for beginners? Classic Mega Man games are known as fairly tough, especially through precise jumps, enemy patterns and bosses you first have to learn to read. Modern entries often soften that on-ramp with assists, checkpoints or difficulty modes. For beginners it usually works best to first get used to one stage, recognise patterns, and not immediately pick the most pure or hardest play style.',
      'Which Mega Man should you play first? Mega Man 11 is the most logical on-ramp for many new players, because it combines modern controls, clear difficulty options and the classic 2D setup. Anyone who wants the origin can look at the Mega Man Legacy Collection, but those games feel stricter and more old fashioned. Fans of faster action are better off starting with Mega Man X, while Battle Network turns more on tactics and deck building.',
      'Which platforms are handy for a game like Mega Man Dual Override? For a fast 2D platformer, low input lag and a good d-pad or analog stick matter more than raw graphical power. On PC, PlayStation and Xbox you often play comfortably on a big screen with a fixed controller. On Nintendo Switch or Switch 2, portable play is attractive, especially for short levels. The best pick mainly depends on your favourite controller and where you usually play.',
    ],
  },
  {
    slug: 'review-wolverine-is-een-fantastisch-gemaakte-game-maar-geen-fantastische-game',
    title: 'Review: Wolverine is a fantastically made game, but not a fantastic game',
    excerpt:
      'Normally Wolverine should be a gimme. Sony’s own games are almost always scored high, the audience swallows them whole, superhero games are almost always a hit these days, and developer Insomniac has a reputation of years of nothing but hits. Past results offer no guarantees for the future, it turns out. Wolverine is anything but a fantastic game.',
    author,
    publishedAt: '2026-09-10',
    category: 'PlayStation',
    tags: ['PlayStation', 'Marvel', 'Review'],
    coverLabel: 'WOLV',
    coverImage: '/covers/articles/wolverine-marvel.jpg',
    gameSlug: 'wolverine-marvel',
    related: [
      { collection: 'reviews', slug: 'wolverine-marvel' },
      { collection: 'news', slug: 'interview-insomniac-games-over-wolverine-reviews-openwereldgames-en-de-grote-lek' },
    ],
    seo: {
      title: 'Review: Wolverine is a fantastically made game, but not a fantastic game',
      description:
        'Marvel’s Wolverine on PS5 scores 6.8: near perfect tech and acting, thin combat, little enemy variety, awful pacing.',
    },
    body: [
      'Score: 6.8 out of 10. Plus: technically almost perfect; a solid story with excellent acting. Minus: middling gameplay; barely any enemy variety; terrible pacing.',
      'Wolverine is a decent game, but never more than that. Top notch graphics and acting lift it a little above average, but we are talking about a game, and in this medium those things are secondary. What it does turn on, the gameplay, lacks the sauce and the salt to get near what we are used to from Insomniac.',
      'It is easy to imagine a less hardcore audience will still have a fine time with the icon hairy down to his lower back. Wolverine is one of the most popular superheroes, and the genuinely solid story you walk through is packed with insanely tight performances from every actor. Liam McIntyre deserves the biggest applause here, not because the Wolverine actor stands head and shoulders above the rest, but because he manages to step out of the shadow of Hugh Jackman (forever the only real Wolverine). Troy Baker lays down a fine Essex, and Krizia Bajos is probably my favourite version of Jean Grey ever.',
      'Technical perfection. Technically it is enough to make you drool until you drown. You do not make a game this pretty unless you put one of the best studios in the world to work for years with an almost endless budget. And so it happened. No ugly unfinished corner, no framedrop in sight, and the way Wolverine comes out of a fight with half torn strips of flesh, adamantium ribs sometimes fully visible, is a feat.',
      'And all that splendour is not limited to the linear levels. In larger, detailed environments such as Japan or the fictional Madripoor, no stone or leaf is left untouched. The coat this game wears is as clean as it gets, even when it is soaked from head to toe in flying blood. With a critical eye you could still say it is too clean, because technically impressive or not, a more pronounced, stylistic face or art direction would not have been out of place. Over time that handsome face even becomes a bit… boring. At least it is consistent, because that stamp also sits on the gameplay.',
      'Leave the wheel alone. For all the positive presentation, in the end it is little more than dressing to disguise a simple button masher action game from 2004 as something of this moment. By the time the credits hit, in about ten hours you have mashed square about 10,000 times, and triangle 5,000 times. The first for normal attacks, the second to leap at one of the many enemies. Those enemies, 90 percent of the time, are either soldiers or soldiers in a ninja costume. That dumb mashing is dutifully mixed with blocking or dodging attacks, but those kinds of systems live or die by the feel those actions give you.',
      'The odd thing is Insomniac never needed to reinvent this wheel. Pretty much every action game, from Bayonetta to Metal Gear Rising and Sekiro, or modern peers such as the just released Onimusha, has this trick worked out to perfection. Wolverine learns nothing from them. Dodging an attack never feels like more than a slightly dumb roll away, while the weird timing of the parry only rarely delivers anything satisfying.',
      'Fine. There are large stretches in Wolverine where the game gets away with mindless mashing. Do not get me wrong, the game is not bad. And the more casual player probably has less experience with similar games that execute almost everything here far better. But anyone who knows the genre regularly sees “mindless fun” turn into simply “mindless”. It does not help that the game constantly hits the brakes. Because it wants you to walk slowly, so there is breathing room for the story. Because it wants you to hunt drawings for a young mutant for, uh, reasons that are undoubtedly very good. Because it worries for the umpteenth time about the character growth of the leads, instead of giving priority to just being a fun game. We are used to Insomniac mastering both.',
      'Normally it is easy to judge (condemn?) a game like this much more harshly, and anyone who believes in the adage “gameplay is king” should stay well away. But Wolverine saves a lot with its journey and attention to detail. The storyline that combines Indiana Jones with the X-Men universe stays tight, a handful of more unique scenes steal the show, and despite the simple nature of the gameplay, I always wanted to continue to see what the next chapter had. Added up that makes a decent ride. But over the top of it sits a thought that will not be shaken from start to finish: this would have been a better comic, film or series than a game.',
      'Marvel’s Wolverine comes out on 15 September for PlayStation 5.',
      'What kind of game is Marvel’s Wolverine? Marvel’s Wolverine is a single player action adventure for PlayStation 5. The game turns on fast close combat, story driven missions and Logan’s violent fighting style. So do not expect an open world game in the style of a big sandbox, but a focused superhero action game with cinematic scenes, familiar Marvel characters and a lot of emphasis on melee fights.',
      'How much does Marvel’s Wolverine cost on PS5? Marvel’s Wolverine has a European recommended price of 79.99 euro for the standard edition. Digital extras or fancier editions can cost more, depending on the version and shop. For most players the standard edition is enough, because it contains the full game. Extra editions are mainly interesting if you care about cosmetic bonuses or digital collectible content.',
      'How does Marvel’s Wolverine sit next to Marvel’s Spider-Man? Marvel’s Wolverine and Marvel’s Spider-Man both come from Insomniac Games, but they aim at a different feel. Spider-Man turns strongly on acrobatics, web swinging and open city exploration, while Wolverine leans heavier on brute close combat and a darker tone. Anyone mainly looking for the smooth freedom of Spider-Man should therefore count on a more compact and harder action adventure.',
      'Why is Marvel’s Wolverine not meant for young children? Marvel’s Wolverine clearly aims at an older audience through the violence, blood and hard tone. The European PEGI rating is 18, which means the game is not meant for minors. That fits the character, but makes the game less suitable as a general family superhero game. Parents are better off checking gameplay footage and the age rating first.',
    ],
  },
  {
    slug: 'gespeeld-final-fantasy-7-revelation-wordt-de-afronding-van-een-legendarische-trilogie',
    title: 'Played: Final Fantasy 7 Revelation will close out a legendary trilogy',
    excerpt:
      'A little over ten years ago it still felt like a dream, the remake of Final Fantasy 7. The legendary role playing game is not merely being remade, it grew into an unimaginably large project. Now that Revelation closes the trilogy, we can cautiously say it is becoming the best remake ever.',
    author,
    publishedAt: '2026-09-10',
    category: 'PlayStation',
    tags: ['PlayStation', 'Final Fantasy', 'Preview'],
    coverLabel: 'FF7',
    coverImage: '/covers/articles/final-fantasy-7-revelation.jpg',
    related: [
      { collection: 'news', slug: 'square-enix-wil-fysieke-games-blijven-maken-ondanks-dat-sony-ermee-stopt' },
      { collection: 'news', slug: 'gespeeld-final-fantasy-resonance-voelt-als-een-warm-dekentje' },
    ],
    seo: {
      title: 'Played: Final Fantasy 7 Revelation will close out a legendary trilogy',
      description:
        'Hands-on with Final Fantasy 7 Revelation at Gamescom. Out 8 April on PS5, Xbox, Switch 2 and PC.',
    },
    body: [
      'I do have to put a large caveat on that. Final Fantasy 7 Remake, Rebirth and apparently also Revelation change so much about the original story that they outgrow the classic “remake”. There are parallel timelines, characters who return or who die, and many more bold adjustments. So far Square Enix has kept fans satisfied cleverly enough, but everything lives or dies by how the many questions the games raise are answered in the last part.',
      'Without giving too much away, director Naoki Hamaguchi says it is at least not a “sequel” to the original game, as some speculated. According to him it becomes more a kind of best of of all Final Fantasy 7 content that has ever appeared, such as the film Advent Children and the spin off Crisis Core. What that exactly means for the grotesque, hopeless ending of the original he will not give away in the surprisingly cool Square Enix booth at Gamescom. One thing is certain: the world we know from both the original and Rebirth has changed a little again.',
      'The same world, but different. That while at the time of Remake, the first part of the trilogy, I still had no nostalgia for the original. Only when I started the Switch version of that original did I understand how that seemingly small story about capitalism, war and the eco terrorists made such an impression back then. The game not only had an impressive amount of systems and choices, but also a hugely cinematic approach and a plot that constantly surprised players with interesting themes. Cloud’s misplaced memories, the relationship between muscle man Barret and his daughter, and the death of beloved Aerith still stay with me, all aspects the remake trilogy expands and adjusts.',
      'Rebirth turned on the feeling of discovery: the moment Cloud leaves Midgar and the story really begins. It is still an odd yet good open world game, which already gives away almost the entire world of the game. That is something Hamaguchi struggled with, but found solutions for in all kinds of ways to make the world we have now visited twice feel fresh:',
      '“The first is the obvious one: we changed a lot about the look, there are visual differences between the two games, and that all lines up with how the story continues. Junon is attacked by Weapon and Weapon does a lot of damage, so you have places where the structure of the city is broken and where you see the traces of that attack. In Gongaga the water has risen and part of it is now underwater.”',
      'That meteor is of course not just a detail: it gives a Zelda: Majora’s Mask kind of atmosphere to the otherwise easygoing game. Everywhere you look in the game world the heavenly body hangs threateningly in the sky, to constantly remind you the end of the world is near. Revelation has no clock that counts down, but given the vague ending of Final Fantasy 7 and the choices the team takes during the remakes, the pressure is high.',
      'From the Highwind you have a good view of the comet, by the way: the airship with which from the start of the game you can look at the complete world from another perspective:',
      '“The second approach was changing how you explore those areas. In Rebirth that was largely what we call horizontal exploration: you travel over land to a place, across a flat plane. You could move freely, but you had no verticality. By adding that vertical element, being able to travel through the air and look at things from above, many locations already felt truly different because of that alone.”',
      'That also makes the Gamescom demo a bit overwhelming, actually. Square Enix encourages us not to dive straight into one of the new areas such as Wutai to follow the story, but to explore the open world with the airship. That is in principle extremely quick, and even makes Revelation feel more like the original and many classic RPGs. The idea behind it, according to Hamaguchi, is that it should reduce “stress”, because despite the sprawling regions you can move everywhere quickly, whether with the ship itself, your parachute or the chocobo beasts.',
      'Finally seeing the complete world of the game from above is a real relief for the fan in me, but as said a lot comes at you. That also has to do with where the demo sits in the story, and because a laundry list of icons and notifications pops up when we land gracefully in familiar Gongaga. There are plenty of hints at things to explore in the world, characters with side missions and a sea of Monster Assessment Instrument notifications to investigate.',
      'That is the point: “This is my own design philosophy, so there is no single right answer, this is just how I approach it. Something I personally do not like in open world games is that you are dumped in a huge world without information, without a hint about what you should do or where you should look, with a design that says: well, if you find something, that is fine. I think that is quite frightening for a lot of people.”',
      'New fit. After half an hour looking for a lost chocobo, Revelation promises to be full of absurd and funny detours again, I do dive into Wutai. Besides being guaranteed some action, it is also one of the few locations not yet translated into the remake. Of course the enthusiastic ninja Yuffie plays an important role on arrival, clearly having been away from home for a long time. Then you also notice a few of the familiar heroes are missing, but for people who know the original that should be no surprise.',
      'Right, arriving in Wutai, which plays an important part in a subplot around the war with Shinra, comes with a number of fights. One of the reasons this remake trilogy is so successful is that it balances perfectly between the turn based combat from the original and faster action from modern parts. You can still perform basic attacks quickly, but you practically freeze time for special skills and magic. You have to know your characters a little for it, but once it clicks there is actually no RPG that does it better.',
      'Then the original was already surprisingly flexible with the different Materia orbs you could select, and Rebirth added Synergy attacks among other things, but Revelation goes a step further. Thanks to the so called Function Integrated Tactical Suitwear (FITS), characters can take on specific roles as in older parts. You have the attacking Warrior, defending Knight, magic specialist Black Mage and Summoner who calls help creatures such as the familiar Ifrit.',
      'Besides each role of course coming with a new outfit, it really gives a totally different dimension to existing characters. A typical fighter such as Yuffie is not limited to Warrior, for example, but can in fact fill every role. In our demo the eccentric pilot Cid is a Black Mage, who with a unique FITS skill can execute spells twice inside a radius. With the now large cast of characters, vampire Vincent Valentine is also along, the possibilities seem endless.',
      'Satisfaction. Honesty also demands that Final Fantasy 7 Revelation cannot really be captured in an hour of play. I pick up little of the weight of the story, how the world has exactly changed, and whether FITS is really a game changer. There are of course also a lot of questions about parallel timelines and certain choices that Revelation finally has to answer. My biggest fear is that I still end up stuck with those questions.',
      'Luckily I also know how the original ends, and that there is an iron foundation to close this exceptional remake trilogy. Naoki Hamaguchi, someone who only played the original as a fan and now leads this gigantic project, after all these years mainly feels satisfaction:',
      '“As you say it is a legendary game. So loved by so many people, with very high expectations, and I am making a remake of that. I am now working on the last piece, on the climax of that project, and that really gives a feeling of satisfaction. That is what I feel now.”',
      'Final Fantasy 7 Revelation comes out on 8 April for PlayStation 5, Xbox Series X and S, Nintendo Switch 2 and PC. Also read our piece on why Square Enix wants to keep making physical games.',
      'Which edition of Final Fantasy 7 Revelation should you buy? For most players the standard edition of Final Fantasy 7 Revelation is the safest choice, because you get the full main game without extra digital bonus content. The Trilogy Edition is mainly interesting if you do not yet own Remake Intergrade and Rebirth. Premium editions make more sense for fans who care about the Story Expansion Pass, digital extras or early access. Physical collector releases are mainly meant for collectors.',
      'How much does Final Fantasy 7 Revelation cost in the Netherlands? The digital standard edition of Final Fantasy 7 Revelation sits in Dutch stores at 79.99 euro. On Xbox the Trilogy Edition is also listed at 94.99 euro, the Premium Edition at 109.99 euro and the Premium Plus Edition at 119.99 euro. Prices at physical shops can differ, especially with preorders, bundles and temporary deals.',
      'Which earlier Final Fantasy 7 games should you play before Revelation? Start with Final Fantasy VII Remake Intergrade and then play Final Fantasy VII Rebirth, because Revelation is the third and closing part of that remake trilogy. Knowledge of the 1997 original is not required, but makes many references, characters and story choices clearer. Crisis Core and Advent Children are extra interesting for fans, but less necessary than the first two remake parts.',
      'How do you choose between PS5, Xbox Series X and S, Switch 2 and PC? Pick mainly the platform on which you own or want to play the first two parts, because saved data can unlock bonus content per platform. PS5 is logical if you already played Remake and Rebirth there. Xbox is attractive if you want to use Xbox Play Anywhere. Switch 2 turns on portability, while PC is interesting if you care about adjustable graphics and store choice.',
      'What do you get with the Story Expansion Pass of Final Fantasy 7 Revelation? The Story Expansion Pass contains two planned story expansions for Final Fantasy 7 Revelation. The first turns on Sephiroth and the second on Vincent and the Turks. Square Enix plans these DLCs between winter 2027 and spring 2028 and says they will also be available separately after release. Anyone who only wants to play the main story does not need to buy the pass immediately.',
    ],
  },
  {
    slug: 'square-enix-wil-fysieke-games-blijven-maken-ondanks-dat-sony-ermee-stopt',
    title: 'Square Enix wants to keep making physical games, even as Sony stops',
    excerpt:
      'Square Enix wants to keep producing physical games where possible. That is what Final Fantasy 7 Revelation director Naoki Hamaguchi says in an interview with ID.',
    author,
    publishedAt: '2026-09-10',
    category: 'PlayStation',
    tags: ['PlayStation', 'Industry', 'Square Enix'],
    coverLabel: 'DISK',
    coverImage: '/covers/articles/final-fantasy-7-revelation.jpg',
    related: [
      { collection: 'news', slug: 'gespeeld-final-fantasy-7-revelation-wordt-de-afronding-van-een-legendarische-trilogie' },
    ],
    seo: {
      title: 'Square Enix wants to keep making physical games, even as Sony stops',
      description:
        'Naoki Hamaguchi says Square Enix will keep physical editions where it can, including Final Fantasy 7 Revelation on disc.',
    },
    body: [
      'Where Sony stops producing physical games for PlayStation consoles from 2028, one of the most prominent directors inside Square Enix says the company wants to keep making physical editions of their games. The director says he fought for it inside the company, which last quarter sold 90.1 percent of its games digitally, and at least wants to defend the culture around physical games.',
      '“I know that when this subject came up earlier, we said there was still a lot of discussion inside the company about whether a disc version even made sense, whether we could even make one, and that we would do our best to get that done where possible, and I know there are fans who worry about how that will play out,” Hamaguchi says at the Square Enix booth at Gamescom.',
      '“I think no outlet has asked about this recently, so I have never answered it either. This is the first time I am making this information public. So we looked into how far it makes sense, whether we can make physical versions. The outcome is that it can, and that we want to.”',
      'Culture. As the main reason the director, whose game Final Fantasy 7 Revelation also still comes out on disc on 8 April, says he finds it important to guard the culture of physical games.',
      '“I always say first that I understand the situation around physical discs,” Hamaguchi explains first. “Physical discs are becoming rarer as an environment, and the number of people who want a disc version is shrinking. That is in a sense a sign of the times, and that is inevitable to a certain extent, I understand that as a fact.',
      'At the same time there is a culture I want to protect. As a developer, when I meet press like you and people from the fan community, someone brings a box and asks if I will sign it, and I find that a really beautiful piece of game culture. That is the first thing I feel as an individual developer: I absolutely want to keep that culture. In that sense it is sad to think it could disappear.”',
      'Hamaguchi also says he would like a physical version of Kingdom Hearts 4, which is due late 2027.',
      'Game key cards. He does still raise one obstacle with the different kinds of physical games. The Nintendo Switch 2 version of Final Fantasy 7 Revelation comes on a game key card: a physical card that requires a (partial) download of the game. Besides digital versions of Switch 2 games loading faster than titles that sit fully on a cartridge, Hamaguchi says it is also a matter of quality:',
      '“I will absolutely not choose to lower the quality of the game to get it on a disc. I am not going to give up the final quality of Revelation, and I am not going to cut anything out to make the game smaller, only to fit inside the disc capacity of a specific platform. Quality comes first.',
      'As I see it now, we will probably land on a physical version where we put as much data on the disc as fits, and have the rest downloaded.”',
      'He does acknowledge that part of the players react negatively to the decision around the Nintendo Switch 2 version:',
      '“I know part of the customers and fans will find it negative that you buy a box and cannot play everything from the disc, a certain number of people will react that way, and that is also completely fair. But as I said at the start: protecting the culture around the physical version is something I absolutely want to defend, and given all the circumstances we work in this seems the best achievable end point. I understand those sounds, but I would really appreciate it if people have understanding for our position here. If we can think of something better, we will.”',
      'Sony stops discs despite criticism. Since the announcement that Sony is stopping physical discs it has received a lot of criticism. Despite that, Sony is pushing through the plans to print no new discs for PlayStation consoles from 2028.',
      'The main reason for the decision is that producing discs costs money per game, while according to Sony currently only fifteen percent of games are sold physically. It also earns more money through digital sales in the PlayStation Store through the lack of competition and of a physical shop in between. Games that come out before 2028, such as Final Fantasy 7 Revelation, can still be reprinted.',
      'What is cheaper: physical games or digital games? That differs per title and per moment. Physical games often have price competition between shops and can get cheaper second hand, while digital games mainly depend on deals in the platform’s online store. On new releases digital prices are regularly more stable, but during big sales they can drop hard. Anyone buying on price therefore compares both forms and also looks at resale value.',
      'How do you choose between physical and digital games? Choose physical if you want to lend games, resell them, collect them or have them visible on the shelf. Choose digital if convenience weighs heavier: no boxes, faster switching between games and always access through your account. Do watch storage space, download size and platform rules. For collectors physical stays more attractive, while many players find digital nicer for daily use.',
      'Which PlayStation 5 do you need for physical games? For physical PlayStation games you need a PS5 with a disc drive. The PS5 Digital Edition is meant for digital games and has no disc slot as standard. On newer model groups, such as the slimmer PS5 Digital Edition and PS5 Pro, a separately sold disc drive can be used if the model is suitable for it. Always check the exact PS5 model before you buy physical games.',
      'What is a game key card on Nintendo Switch 2? A game key card is a physical Nintendo Switch 2 card that gives access to a game, but where the game data first has to be downloaded. The card then has to stay in the console to play. It therefore feels partly physical and partly digital. For collectors that is less attractive than a full cartridge, but for publishers it can help with larger games.',
      'Why do collectors want to keep physical games? Collectors care about physical games because a box, cover, cartridge or disc is more than only access to software. The object has collector value, can be signed and stays a visible part of a collection. Control also plays a part: a physical game can often be lent or sold more easily. On modern releases it still matters whether the full game sits on the medium.',
      'How does returning digital PlayStation games work? Digital PlayStation purchases have stricter return rules than many physical purchases. In practice you usually cannot ask for a digital game back once you have started downloading or streaming it, except if there is a defective product. Preorders and unused purchases leave more room, but the exact conditions depend on the moment of purchase and the type of content.',
    ],
  },
  {
    slug: 'hideo-kojimas-physint-wordt-nu-gemaakt-met-xbox-nadat-playstation-zich-heeft-teruggetrokken',
    title: 'Hideo Kojima’s Physint is now being made with Xbox, after PlayStation pulled out',
    excerpt:
      'The upcoming spy game Physint from Metal Gear Solid and Death Stranding maker Hideo Kojima was first going to be produced with Sony PlayStation, but after the company stepped away from the project Kojima Productions went in with Xbox.',
    author,
    publishedAt: '2026-09-10',
    category: 'Xbox',
    tags: ['Xbox', 'Kojima', 'Industry'],
    coverLabel: 'PHYS',
    coverImage: '/covers/articles/physint.jpg',
    related: [
      { collection: 'news', slug: 'blizzard-bevestigt-eindelijk-een-nieuwe-starcraft-game-maar-je-moet-er-nog-jaren-op-wachten' },
    ],
    seo: {
      title: 'Hideo Kojima’s Physint is now being made with Xbox, after PlayStation pulled out',
      description:
        'PlayStation cancelled Physint in mid June. Kojima Productions found Xbox as the new partner for the spy game.',
    },
    body: [
      'That news broke earlier through the X profiles of Kojima himself, Kojima Productions, PlayStation and Xbox. First Hideo Kojima said the following in his post:',
      '“As just confirmed through our official channels [see below], in mid June of this year we got an unexpected message from PlayStation Studios that they were going to cancel the Physint project. Physint is an important project for both me personally and Kojima Productions. Determined to keep the project alive, we have spent the past three months searching nonstop for a new partner.',
      'During seeking advice and many negotiations with people from different fields, we found in Xbox a partner with whom our vision for the future lines up, and we have decided to go in with them once again. Rest assured that development of Physint, our genre defining action spy game, is still ongoing.”',
      'Why is PlayStation Studios pulling out? Physint was announced in January 2024 as a collaboration between Kojima Productions and PlayStation Studios. The two parties had already worked together on Kojima’s Death Stranding games, and Physint would mean a return to the spy genre the legendary Japanese developer grew big on. He is, after all, the creative brain behind the Metal Gear Solid series.',
      'Hideo Kojima has described the project as a culmination of his work over the years, and from the bits of information shared over the years it looks like an ambitious project. At least it was clear the game was being made with Columbia Pictures, a subdivision of Sony’s film arm. The goal of the project was thereby also clear:',
      '“[Physint] aims to blur the divide between film and video games in visual style, narrative depth, thematic richness and production scale, including the cast, the acting, the fashion and the sound.”',
      'High price tags. Although PlayStation Studios and Kojima Productions do not name a specific reason why the collaboration fell through, it may have something to do with the last point in the list above: the production value of Physint.',
      'The scale and ambition of the project was always going to be large, and it is quite possible PlayStation no longer wanted the required investment. The last game from Kojima Productions, Death Stranding 2: On the Beach, has gone under the counter around two million times, which would mean an estimated take of around 150 million dollars.',
      'An average blockbuster in the film world already has a budget between 100 and 150 million dollars, often more. Given you have to build sets, produce visual effects, maintain a cast with often very expensive actors and crew, you hit a high figure.',
      'Game development is no cheap operation either. Even when you can use existing tools, such as how Kojima Productions used the Decima Engine to bring Death Stranding to life, the same engine Guerrilla Games uses for the Horizon games.',
      'The budget of Death Stranding 2 is unknown, but perhaps the return on investment, what you get out of an investment, was not promising enough to keep supporting Kojima’s passion project. PlayStation Studios has taken a number of heavy losses in recent years because a renewed focus on live service games is not working out so well.',
      'Of course the hero shooter Concord was taken offline two weeks after release, but Marathon from Destiny maker Bungie was also no monster success and development of Guerrilla Games’ Horizon: Hunter’s Gathering was recently overhauled. Perhaps Physint, despite the prestige of the developer behind it, was too risky a project for the company.',
      'Once again a collaboration with Xbox. Xbox and its CEO Asha Sharma, newly appointed earlier this year, are at least delighted about the new collaboration with Kojima. Physint is also not the first time the two parties join hands: Kojima Productions’ next game is OD, a horror game that is also being developed with Xbox Game Studios.',
      'Whether Physint will be an Xbox exclusive title is still unknown, but it is almost certain the game will only come out for the next console generation. Production of Physint can easily still take five years. If development of the game is not hit too hard by the partner switch, of course.',
      'A lot is still unclear, such as which game engine Kojima Productions will use if they no longer have access to Guerrilla’s Decima, and to what extent Columbia Pictures was actually essential for development of the game and its ambitious mix of film and games. The question is also how that is absorbed inside Xbox and Microsoft.',
      'Worth noting at least is that Microsoft is apparently talking with various studios to produce projects based on their IPs. According to Xbox’s own update around the Kojima Productions collaboration, the companies are also going in together on film and TV productions.',
      'In the meantime Kojima Productions is at least not sitting still. Besides work on OD, the first steps into the wider entertainment world are also being taken with two Death Stranding related projects. First the animated film Death Stranding: Mosquito, which is currently being produced and of which a teaser can be watched below.',
      'Besides that, a live action Death Stranding film is being worked on with film studio A24, directed by A Quiet Place: Day One and The Death of Robin Hood maker Michael Sarnoski. He recently said preproduction of the film starts sometime in the coming month.',
      'What kind of game is Physint? Physint is an upcoming action spy game from Kojima Productions, Hideo Kojima’s studio. The game is positioned as a modern return to the spy genre, but without the Metal Gear name. Official details about gameplay, missions, playable characters and a release date are still limited. What is clear is that Kojima expressly sees the project as a crossing between cinematic presentation and interactive action.',
      'Which platforms will Physint get? There is still no definitive platform list confirmed for Physint. Since September 2026 Xbox is the new partner and publisher, but that does not automatically mean the game only appears on Xbox consoles. As long as Kojima Productions and Xbox name no concrete platforms, a PC release or wider availability also stays uncertain. For Dutch players that mainly means: wait for official shop pages before you decide on a purchase.',
      'How does Physint differ from Metal Gear Solid? Physint and Metal Gear Solid mainly share the spy theme and the creative background of Hideo Kojima. Metal Gear Solid is however an existing Konami series, while Physint is a new project from Kojima Productions. Physint therefore cannot simply use the same characters, names or storylines. Expect more a spiritual successor in tone and ambition than an official continuation of Metal Gear.',
      'What does a publisher switch mean for development of a game? A publisher switch can have large consequences for budget, planning, tech and platform choices. In some cases the core of the game stays standing, but contracts, marketing plans or used technology have to be looked at again. On a large project such as Physint that can cost months of extra alignment. At the same time a new publisher can save a project when the original partner drops out.',
      'Why are game studios working on films and series more often? Games are treated more and more as entertainment brands, not only as standalone releases. A film or series can make a world, character or studio better known with an audience that games less itself. For studios such as Kojima Productions that fits a cinematic way of telling. The risk is that projects become more expensive and more complex, especially when game development and audiovisual production have to be aligned at the same time.',
    ],
  },
  {
    slug: 'had-nintendo-beter-een-direct-kunnen-doen',
    title: 'Should Nintendo have done one Direct?',
    excerpt:
      'This week Nintendo aired no fewer than two Direct presentations: one around Zelda’s birthday, and a general one. In Bonuslevel Cody and Jacco react this week to both presentations, and they mainly wonder: should this not have been one presentation?',
    author,
    publishedAt: '2026-09-10',
    category: 'Nintendo',
    tags: ['Nintendo', 'Direct', 'Opinion'],
    coverLabel: 'DIR',
    coverImage: '/covers/articles/zelda-ocarina-of-time-switch-2.png',
    related: [
      { collection: 'news', slug: 'nintendo-direct-van-september-2026-de-trailers-en-aankondigingen-op-een-rij' },
      { collection: 'news', slug: 'the-legend-of-zelda-ocarina-of-time-remake-komt-op-5-november-naar-switch-2' },
    ],
    seo: {
      title: 'Should Nintendo have done one Direct?',
      description:
        'Two Nintendo Directs in one week: a Zelda 40th show and a general lineup. Should they have been one presentation?',
    },
    body: [
      'Anticipation for a Nintendo Direct is always huge, sometimes against better judgement. Nintendo does sit in a unique position in the product life cycle to announce the next load of games, and leave the previous platform behind for good. Ahead of this week’s Directs we still knew remarkably little about next year, besides titles such as Xenoblade Genesis and Pokémon Winds and Waves.',
      'On top of that the company still had to unpack its biggest game of 2026, The Legend of Zelda: Ocarina of Time. So it took the time in a separate presentation to mainly highlight that game, then make the remaining announcements on Wednesday afternoon.',
      'Full, yet empty. As you can hear in the podcast below, the reveal of the remake, and its November release date, two weeks before GTA 6, landed like a bomb. From the visual style to the improvements: this autumn we will relive one of the best games ever in modern form.',
      'But the feeling also lingered that not all that much was shown for the fortieth anniversary of the series. There is a concert series, but no substantial information about the Zelda film or other long awaited games. The general Nintendo Direct was quite full, but mainly with ports, rereleases and Switch 2 versions of existing games.',
      'Still, Metroid Ravenous and Kirby and the World Beyond made up for a lot. Metroid as a follow up to the outstanding Metroid Dread, with an apparently new approach, and Kirby as an open world follow up to the wonderful Forgotten Land. The titles kick off 2027 together in a positive way for Switch 2 owners.',
      'One presentation. Still, Nintendo might have made more of an impression this week by trimming both presentations a little and merging them into one convincing Direct. Of course many more parties are involved in planning such a presentation than only the company itself, and it changes nothing about the lineup, but maybe we would still have liked to see it differently.',
      'In any case listen below to the extensive analyses of both Directs, and keep your ears open for yet another full week for Bonuslevel.',
      'What is a Nintendo Direct? A Nintendo Direct is a video presentation in which Nintendo shows new games, updates and release dates. The broadcasts differ in length and subject: sometimes everything turns on one game or series, sometimes on a broader lineup for Nintendo Switch 2 and Nintendo Switch. For players, Directs are mainly handy to see which titles are coming soon and whether a console purchase or preorder is worth it.',
      'How do you decide whether buying a Nintendo Switch 2 now is wise? Look first at 3 things: the games you really want to play, support for your existing Switch library, and the period in which new exclusives appear. Nintendo Switch 2 also plays compatible Nintendo Switch games, but some titles may not work or not fully. So do not only wait for standalone announcements, but judge whether the available and announced lineup fits how you play.',
      'Which Nintendo Switch games work on Nintendo Switch 2? Nintendo Switch 2 can play compatible physical and digital Nintendo Switch games besides its own Switch 2 games. That does not mean every old game works without issues: Nintendo reports that certain Switch games may not be supported or not fully compatible. When in doubt, check the compatibility information before you buy a game or see your old collection as the main reason to switch.',
      'What is the difference between a Switch 2 game and a Switch 2 Edition game? A Nintendo Switch 2 game is made or released for the new console. A Nintendo Switch 2 Edition is an improved version of an existing Switch game, often as a bundle of the original game with an upgrade pack. If you already own the original Switch game, you can buy an upgrade pack on selected titles to use Nintendo Switch 2 improvements.',
      'Why are release dates from a Nintendo Direct important for purchase advice? Release dates make a Direct concrete: they show when you actually get something from a console or game. A strong announcement without a date can be interesting, but helps less with planning or buying. For purchase advice it is therefore not only how many games Nintendo shows, but especially which games appear within 6 to 12 months and whether those fit your tastes.',
    ],
  },
  {
    slug: 'nintendo-direct-van-september-2026-de-trailers-en-aankondigingen-op-een-rij',
    title: 'Nintendo Direct of September 2026: the trailers and announcements in a row',
    excerpt:
      'Nintendo has aired a brand new Direct presentation, full of updates and announcements of upcoming games, including Metroid Ravenous and a Kirby open world game.',
    author,
    publishedAt: '2026-09-09',
    category: 'Nintendo',
    tags: ['Nintendo', 'Direct', 'Releases'],
    coverLabel: 'NINT',
    coverImage: '/covers/articles/metroid-ravenous.jpg',
    related: [
      { collection: 'news', slug: 'had-nintendo-beter-een-direct-kunnen-doen' },
      { collection: 'news', slug: 'the-legend-of-zelda-ocarina-of-time-remake-komt-op-5-november-naar-switch-2' },
    ],
    seo: {
      title: 'Nintendo Direct of September 2026: the trailers and announcements in a row',
      description:
        'September 2026 Nintendo Direct: Metroid Ravenous, Kirby and the World Beyond, and the rest of the trailers in a row.',
    },
    body: [
      'Earlier Nintendo already put the remake of The Legend of Zelda: Ocarina of Time extensively in the spotlight with its own Direct, celebrating the fortieth anniversary of that franchise. The general Direct presentation then offered three quarters of an hour of trailers and announcements from both Nintendo itself and various partners. All the news sits below in a row.',
      'Metroid Ravenous comes to Switch 2 on 28 January. Nintendo has announced that a new two dimensional Metroid game, with the subtitle Ravenous, comes out in January 2027. In this follow up to the beloved Metroid Dread, bounty hunter Samus is still trying to get home, but she is stranded on an alien moon. Mysterious figures there seem to work against her.',
      'To escape, Samus seems to “feed” on her opponents. In the footage you see she essentially absorbs enemies, and that her look thereby becomes a little more monstrous bit by bit. Smooth platforming gameplay is shown again, and in one of the shots you look over Samus’s shoulder in what may be a third person perspective.',
      'Open world game Kirby and the World Beyond announced. Next year the Kirby franchise celebrates its 35th birthday, and as part of that the open world game Kirby and the World Beyond comes out. The first trailer shows an idyllic, colourful world in which Kirby can walk and float freely, while as usual he inhales enemies to steal their powers.',
      'The pink blob then finds out he is inside a kind of dome, which he manages to break through with a gigantic sword to reveal an even larger world.',
      'Mario Kart World gets free SNES courses in VS mode. Players of Mario Kart World can get to work today with courses inspired by tracks from the original Mario Kart game. These tracks can be selected in VS mode, and also contain the question mark blocks on the ground, instead of the familiar colourful item boxes modern Mario Kart games use. Two new routes for Knockout Tour mode have also been added with this update.',
      'New trailer and the release date of the Monster Hunter: Wilds port revealed. A new trailer of the upcoming Switch 2 version of Monster Hunter Wilds was shown, which comes to the console on 4 December. The Ascendance expansion revealed during the recent PlayStation State of Play later also comes to Switch 2.',
      'Monster Hunter Wilds already came out in early 2025 for PlayStation 5, Xbox Series X and PC. The Ascendance expansion for the game was also recently revealed, due in 2027. As with previous games in the series, Monster Hunter Wilds lets players hunt monsters. There are more details in the monsters and game world than ever before. New is that players can carry an extra weapon on their mount while hunting, which gives more choice in how a monster is brought down. There is also a special Focus mode to find weak spots on monsters.',
      'Popular “friendslop” game Meccha Chameleon comes to Switch 2 today. Friendslop is a catch all term for relatively simple indie games you mostly play together with friends. Meccha Chameleon is one of the most recent hits in this genre. The game turns on hiding in different environments, where players have to colour and draw over themselves, so they are not found. Now Meccha Chameleon can therefore also be played on a console.',
      'The Switch 2 version supports crossplay with other platforms, and you can use the mouse functionality.',
      'New content for various Nintendo games shown. During the Direct it was announced that the second content update as part of the Pokémon Pokopia Expansion Pack comes out later in 2026, and that accessories to dress your Ditto and other Pokémon sit at the centre of it.',
      'More Nintendo games are getting updates, so Hyrule Warriors: Age of Calamity gets a Definitive Edition for Nintendo Switch 2. All DLC is included in this version, with better performance on the new console and a new difficulty: Calamity Mode.',
      'The remake of Star Fox: Lylat Wars, now mainly known as Star Fox (2026), also gets a free update, which among other things makes it possible to play Battle Mode with local splitscreen. That way you and three friends can blast at the same time.',
      'Even more trailers. With a presentation of three quarters of an hour a particularly large amount of material always goes by, so below sit the rest of the trailers and announcements that came by in the Direct.',
      'Star Fox Adventures comes to GameCube Nintendo Classics.',
      'Pikmin 4 gets a Nintendo Switch 2 edition that comes out on 12 November.',
      'Professor Layton and the New World of Steam finally has a release date again: 10 December.',
      'Silent Hill 2 Remake developer announces Onyx: The Dark Grip.',
      'Disney Dreamlight Valley: The Keepsake Sea expansion comes out in November.',
      'Mountain climbing game Cairn clambers to Nintendo Switch 2 in 2027.',
      'Resident Evil 2, 3 and 4 get new editions on 16 October.',
      'Tomb Raider: Legacy of Atlantis also comes to Switch 2.',
      'Nintendo Switch Sports Resort shows free roam on Wuhu Island.',
      'Persona 4 Revival also comes to Switch 2 on 20 May, Persona 6 also confirmed for the platform.',
      'Kingdom Come: Deliverance 2 Royal Edition comes to Switch 2 in 2027.',
      'Crisis Core: Final Fantasy 7 Reunion now has a Switch 2 version.',
      'A remake of Yo-Kai Watch 2: Haunted Domain is on the way.',
      'Stage Fright from the Overcooked makers shown.',
      'The Switch 2 edition of Xenoblade Chronicles 3 contains a Vampire Survivors like mode.',
      'Rhythm game Ondeh Ondeh Kaya’s Tasty Tale announced.',
      'Sell the Joker a slap: Lego Batman: Legacy of the Dark Knight comes to Switch 2 on 18 September.',
      'Proto Man revealed for Mega Man: Dual Override.',
      'Eternal Anima looks like a slick top down RPG.',
      'Yu-Gi-Oh! Tag Force GX lands on Switch 2 on 16 February.',
      'Fire Emblem: Fortune’s Weave shown once more ahead of release.',
      'The Witcher 3: Wild Hunt Remastered reconfirmed for Switch 2.',
      'Danganronpa 2x2 comes out on 14 January.',
      'Fatal Fury: City of the Wolves also still comes to Switch 2 this year.',
      'Shoot around a lot in Metal Slug Ultimate Collection.',
      'Romancing SaGa 3: Destinies United has also been revealed.',
      'What is a Nintendo Direct? A Nintendo Direct is an online video presentation in which Nintendo shares new games, updates, trailers and sometimes release dates. Length differs per broadcast: some presentations last about 15 minutes, while larger general Directs can sit around 45 minutes. Nintendo often focuses on its own titles, but there is also room for games from external publishers and indie studios.',
      'Which Nintendo Switch games work on the Nintendo Switch 2? According to Nintendo the Nintendo Switch 2 plays many physical and digital Nintendo Switch games, but not every game works fully the same. Some titles have compatibility problems or require an update. There are also free updates and paid upgrade packs that can add extra content or better performance when you play the game on Switch 2.',
      'What does Nintendo Switch Online cost in the Netherlands? Nintendo Switch Online costs 19.99 euro per year in the Netherlands for an individual standard membership. The Expansion Pack costs 39.99 euro per year. For families there are yearly subscriptions for up to 8 Nintendo accounts: 34.99 euro for standard and 69.99 euro with Expansion Pack. Prices can change, so check them in the eShop before buying.',
      'Why do some Nintendo games appear physically later than digitally? A digital release can be available faster because no production, distribution and shop stock is needed. With physical editions, cartridges, packaging, logistics and regional stock play a part. Publishers sometimes also choose to test digitally first, especially with smaller games. For collectors physical stays attractive, but anyone who wants to play immediately is often fastest digitally.',
    ],
  },
]
